// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type AttachActivityRequest struct {
	// Comma-separated list of entities which the activity primarily concerns
	Entities []string `queryParam:"style=form,explode=false,name=entities"`
	// Activity Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (a *AttachActivityRequest) GetEntities() []string {
	if a == nil {
		return nil
	}
	return a.Entities
}

func (a *AttachActivityRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

// AttachActivityResponseBody - A generic error returned by the API
type AttachActivityResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (a *AttachActivityResponseBody) GetError() *string {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AttachActivityResponseBody) GetStatus() *int64 {
	if a == nil {
		return nil
	}
	return a.Status
}

type AttachActivityResponse struct {
	// Success
	BaseActivityItem *shared.BaseActivityItem
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *AttachActivityResponseBody
}

func (a *AttachActivityResponse) GetBaseActivityItem() *shared.BaseActivityItem {
	if a == nil {
		return nil
	}
	return a.BaseActivityItem
}

func (a *AttachActivityResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AttachActivityResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}

func (a *AttachActivityResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AttachActivityResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AttachActivityResponse) GetObject() *AttachActivityResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
