// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"net/http"
)

type AutocompleteRequest struct {
	// Autocomplete attribute
	Attribute string `queryParam:"style=form,explode=true,name=attribute"`
	// Input to autocomplete
	Input *string `queryParam:"style=form,explode=true,name=input"`
	// Maximum number of results to return
	Size *int64 `default:"10" queryParam:"style=form,explode=true,name=size"`
	// Limit results to entity schema
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (a AutocompleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutocompleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"attribute"}); err != nil {
		return err
	}
	return nil
}

func (a *AutocompleteRequest) GetAttribute() string {
	if a == nil {
		return ""
	}
	return a.Attribute
}

func (a *AutocompleteRequest) GetInput() *string {
	if a == nil {
		return nil
	}
	return a.Input
}

func (a *AutocompleteRequest) GetSize() *int64 {
	if a == nil {
		return nil
	}
	return a.Size
}

func (a *AutocompleteRequest) GetSlug() *string {
	if a == nil {
		return nil
	}
	return a.Slug
}

type ResultsType string

const (
	ResultsTypeStr      ResultsType = "str"
	ResultsTypeBoolean  ResultsType = "boolean"
	ResultsTypeMapOfAny ResultsType = "mapOfAny"
)

type Results struct {
	Str      *string        `queryParam:"inline,name=results"`
	Boolean  *bool          `queryParam:"inline,name=results"`
	MapOfAny map[string]any `queryParam:"inline,name=results"`

	Type ResultsType
}

func CreateResultsStr(str string) Results {
	typ := ResultsTypeStr

	return Results{
		Str:  &str,
		Type: typ,
	}
}

func CreateResultsBoolean(boolean bool) Results {
	typ := ResultsTypeBoolean

	return Results{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateResultsMapOfAny(mapOfAny map[string]any) Results {
	typ := ResultsTypeMapOfAny

	return Results{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *Results) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ResultsTypeStr
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = ResultsTypeBoolean
		return nil
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = ResultsTypeMapOfAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Results", string(data))
}

func (u Results) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type Results: all fields are null")
}

// AutocompleteResponseBody - Success
type AutocompleteResponseBody struct {
	Hits    *float64  `json:"hits,omitempty"`
	Results []Results `json:"results,omitempty"`
}

func (a *AutocompleteResponseBody) GetHits() *float64 {
	if a == nil {
		return nil
	}
	return a.Hits
}

func (a *AutocompleteResponseBody) GetResults() []Results {
	if a == nil {
		return nil
	}
	return a.Results
}

type AutocompleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *AutocompleteResponseBody
}

func (a *AutocompleteResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutocompleteResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutocompleteResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutocompleteResponse) GetObject() *AutocompleteResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
