// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type BulkDeleteClassificationsRequestBody struct {
	ClassificationIds []string `json:"classification_ids,omitempty"`
	// Job ID for tracking the status of a bulk operation request
	JobID *string `json:"job_id,omitempty"`
}

func (o *BulkDeleteClassificationsRequestBody) GetClassificationIds() []string {
	if o == nil {
		return nil
	}
	return o.ClassificationIds
}

func (o *BulkDeleteClassificationsRequestBody) GetJobID() *string {
	if o == nil {
		return nil
	}
	return o.JobID
}

// BulkDeleteClassificationsResponseBody - A generic error returned by the API
type BulkDeleteClassificationsResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *BulkDeleteClassificationsResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *BulkDeleteClassificationsResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type BulkDeleteClassificationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the job id for the async job and current status
	TaxonomyBulkJobTriggerResponse *shared.TaxonomyBulkJobTriggerResponse
	// Too many requests
	Object *BulkDeleteClassificationsResponseBody
}

func (o *BulkDeleteClassificationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BulkDeleteClassificationsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *BulkDeleteClassificationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BulkDeleteClassificationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *BulkDeleteClassificationsResponse) GetTaxonomyBulkJobTriggerResponse() *shared.TaxonomyBulkJobTriggerResponse {
	if o == nil {
		return nil
	}
	return o.TaxonomyBulkJobTriggerResponse
}

func (o *BulkDeleteClassificationsResponse) GetObject() *BulkDeleteClassificationsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
