// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type CancelBulkActionRequest struct {
	// Job ID of the bulk operation to cancel
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (c *CancelBulkActionRequest) GetJobID() string {
	if c == nil {
		return ""
	}
	return c.JobID
}

// CancelBulkActionResponseBody - A generic error returned by the API
type CancelBulkActionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (c *CancelBulkActionResponseBody) GetError() *string {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *CancelBulkActionResponseBody) GetStatus() *int64 {
	if c == nil {
		return nil
	}
	return c.Status
}

type CancelBulkActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	TaxonomyBulkJob *shared.TaxonomyBulkJob
	// Too many requests
	Object *CancelBulkActionResponseBody
}

func (c *CancelBulkActionResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CancelBulkActionResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}

func (c *CancelBulkActionResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CancelBulkActionResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CancelBulkActionResponse) GetTaxonomyBulkJob() *shared.TaxonomyBulkJob {
	if c == nil {
		return nil
	}
	return c.TaxonomyBulkJob
}

func (c *CancelBulkActionResponse) GetObject() *CancelBulkActionResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
