// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

// CreateSchemaCapabilityResponseBody - A generic error returned by the API
type CreateSchemaCapabilityResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (c *CreateSchemaCapabilityResponseBody) GetError() *string {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *CreateSchemaCapabilityResponseBody) GetStatus() *int64 {
	if c == nil {
		return nil
	}
	return c.Status
}

type CreateSchemaCapabilityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	EntityCapabilityWithCompositeID *shared.EntityCapabilityWithCompositeID
	Headers                         map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Too many requests
	Object *CreateSchemaCapabilityResponseBody
}

func (c *CreateSchemaCapabilityResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateSchemaCapabilityResponse) GetEntityCapabilityWithCompositeID() *shared.EntityCapabilityWithCompositeID {
	if c == nil {
		return nil
	}
	return c.EntityCapabilityWithCompositeID
}

func (c *CreateSchemaCapabilityResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}

func (c *CreateSchemaCapabilityResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateSchemaCapabilityResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateSchemaCapabilityResponse) GetObject() *CreateSchemaCapabilityResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
