// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteSchemaRequest struct {
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (d *DeleteSchemaRequest) GetSlug() string {
	if d == nil {
		return ""
	}
	return d.Slug
}

// DeleteSchemaResponseBody - A generic error returned by the API
type DeleteSchemaResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (d *DeleteSchemaResponseBody) GetError() *string {
	if d == nil {
		return nil
	}
	return d.Error
}

func (d *DeleteSchemaResponseBody) GetStatus() *int64 {
	if d == nil {
		return nil
	}
	return d.Status
}

type DeleteSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Too many requests
	Object *DeleteSchemaResponseBody
}

func (d *DeleteSchemaResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteSchemaResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}

func (d *DeleteSchemaResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteSchemaResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteSchemaResponse) GetObject() *DeleteSchemaResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
