// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type DeleteEntityRequest struct {
	// Activity to include in event feed
	ActivityID *shared.ActivityIDQueryParam `queryParam:"style=form,explode=true,name=activity_id"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Permanently deletes the entity when set to `true`
	Purge *bool `default:"false" queryParam:"style=form,explode=true,name=purge"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (d DeleteEntityRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteEntityRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DeleteEntityRequest) GetActivityID() *shared.ActivityIDQueryParam {
	if o == nil {
		return nil
	}
	return o.ActivityID
}

func (o *DeleteEntityRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteEntityRequest) GetPurge() *bool {
	if o == nil {
		return nil
	}
	return o.Purge
}

func (o *DeleteEntityRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type DeleteEntityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteEntityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteEntityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteEntityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
