// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type ExportEntitiesRequest struct {
	EntitySearchParams *shared.EntitySearchParams `request:"mediaType=application/json"`
	// Pass 'true' to generate import template
	IsTemplate *bool `queryParam:"style=form,explode=true,name=is_template"`
	// Export Job Id to get the result
	JobID *string `queryParam:"style=form,explode=true,name=job_id"`
	// Export headers translation language
	Language *string `queryParam:"style=form,explode=true,name=language"`
}

func (e *ExportEntitiesRequest) GetEntitySearchParams() *shared.EntitySearchParams {
	if e == nil {
		return nil
	}
	return e.EntitySearchParams
}

func (e *ExportEntitiesRequest) GetIsTemplate() *bool {
	if e == nil {
		return nil
	}
	return e.IsTemplate
}

func (e *ExportEntitiesRequest) GetJobID() *string {
	if e == nil {
		return nil
	}
	return e.JobID
}

func (e *ExportEntitiesRequest) GetLanguage() *string {
	if e == nil {
		return nil
	}
	return e.Language
}

// ExportEntitiesResponseBody - A generic error returned by the API
type ExportEntitiesResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (e *ExportEntitiesResponseBody) GetError() *string {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *ExportEntitiesResponseBody) GetStatus() *int64 {
	if e == nil {
		return nil
	}
	return e.Status
}

type ExportEntitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Too many requests
	Object *ExportEntitiesResponseBody
}

func (e *ExportEntitiesResponse) GetContentType() string {
	if e == nil {
		return ""
	}
	return e.ContentType
}

func (e *ExportEntitiesResponse) GetHeaders() map[string][]string {
	if e == nil {
		return map[string][]string{}
	}
	return e.Headers
}

func (e *ExportEntitiesResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *ExportEntitiesResponse) GetRawResponse() *http.Response {
	if e == nil {
		return nil
	}
	return e.RawResponse
}

func (e *ExportEntitiesResponse) GetObject() *ExportEntitiesResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
