// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type FreezeSchemaRequestBody struct {
	// Freeze to a specific version ID. Defaults to the current version.
	VersionID *string `json:"version_id,omitempty"`
}

func (f *FreezeSchemaRequestBody) GetVersionID() *string {
	if f == nil {
		return nil
	}
	return f.VersionID
}

type FreezeSchemaRequest struct {
	RequestBody *FreezeSchemaRequestBody `request:"mediaType=application/json"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (f *FreezeSchemaRequest) GetRequestBody() *FreezeSchemaRequestBody {
	if f == nil {
		return nil
	}
	return f.RequestBody
}

func (f *FreezeSchemaRequest) GetSlug() string {
	if f == nil {
		return ""
	}
	return f.Slug
}

// FreezeSchemaResponseBody - A generic error returned by the API
type FreezeSchemaResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (f *FreezeSchemaResponseBody) GetError() *string {
	if f == nil {
		return nil
	}
	return f.Error
}

func (f *FreezeSchemaResponseBody) GetStatus() *int64 {
	if f == nil {
		return nil
	}
	return f.Status
}

type FreezeSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Schema frozen successfully
	EntitySchemaItem *shared.EntitySchemaItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *FreezeSchemaResponseBody
}

func (f *FreezeSchemaResponse) GetContentType() string {
	if f == nil {
		return ""
	}
	return f.ContentType
}

func (f *FreezeSchemaResponse) GetEntitySchemaItem() *shared.EntitySchemaItem {
	if f == nil {
		return nil
	}
	return f.EntitySchemaItem
}

func (f *FreezeSchemaResponse) GetStatusCode() int {
	if f == nil {
		return 0
	}
	return f.StatusCode
}

func (f *FreezeSchemaResponse) GetRawResponse() *http.Response {
	if f == nil {
		return nil
	}
	return f.RawResponse
}

func (f *FreezeSchemaResponse) GetObject() *FreezeSchemaResponseBody {
	if f == nil {
		return nil
	}
	return f.Object
}
