// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type GetActivityRequest struct {
	// Activity Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Pagination offset for operations
	//
	OperationsFrom *int64 `default:"0" queryParam:"style=form,explode=true,name=operations_from"`
	// Maximum number of operations to include in response (default: 10)
	//
	OperationsSize *int64 `default:"25" queryParam:"style=form,explode=true,name=operations_size"`
}

func (g GetActivityRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetActivityRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetActivityRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetActivityRequest) GetOperationsFrom() *int64 {
	if g == nil {
		return nil
	}
	return g.OperationsFrom
}

func (g *GetActivityRequest) GetOperationsSize() *int64 {
	if g == nil {
		return nil
	}
	return g.OperationsSize
}

// GetActivityResponseBody - A generic error returned by the API
type GetActivityResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetActivityResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetActivityResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetActivityResponse struct {
	// Success
	ActivityItem *shared.ActivityItem
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *GetActivityResponseBody
}

func (g *GetActivityResponse) GetActivityItem() *shared.ActivityItem {
	if g == nil {
		return nil
	}
	return g.ActivityItem
}

func (g *GetActivityResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetActivityResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetActivityResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetActivityResponse) GetObject() *GetActivityResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
