// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type GetElasticClusterForOrgRequest struct {
	// The organization to fetch the cluster assigment
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

func (o *GetElasticClusterForOrgRequest) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

type GetElasticClusterForOrgResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	ESClusterAssignment *shared.ESClusterAssignment
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetElasticClusterForOrgResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetElasticClusterForOrgResponse) GetESClusterAssignment() *shared.ESClusterAssignment {
	if o == nil {
		return nil
	}
	return o.ESClusterAssignment
}

func (o *GetElasticClusterForOrgResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetElasticClusterForOrgResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
