// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"net/http"
)

type GetJSONSchemaRequest struct {
	Dereference *bool `default:"false" queryParam:"style=form,explode=true,name=dereference"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (g GetJSONSchemaRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetJSONSchemaRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"slug"}); err != nil {
		return err
	}
	return nil
}

func (g *GetJSONSchemaRequest) GetDereference() *bool {
	if g == nil {
		return nil
	}
	return g.Dereference
}

func (g *GetJSONSchemaRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

// GetJSONSchemaResponseBody - Success
type GetJSONSchemaResponseBody struct {
}

type GetJSONSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *GetJSONSchemaResponseBody
}

func (g *GetJSONSchemaResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJSONSchemaResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJSONSchemaResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetJSONSchemaResponse) GetObject() *GetJSONSchemaResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
