// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type GetRelationsV2Request struct {
	// List of entity fields to include in results
	Fields []string `queryParam:"style=form,explode=true,name=fields"`
	// Starting page number
	From *int64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	// When true, enables entity hydration to resolve nested $relation & $relation_ref references in-place.
	Hydrate *bool `default:"false" queryParam:"style=form,explode=true,name=hydrate"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// When true, includes reverse relations in response (other entities pointing to this entity)
	IncludeReverse *bool `default:"false" queryParam:"style=form,explode=true,name=include_reverse"`
	// Input to filter search results
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Number of results to return per page
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (g GetRelationsV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRelationsV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id", "slug"}); err != nil {
		return err
	}
	return nil
}

func (g *GetRelationsV2Request) GetFields() []string {
	if g == nil {
		return nil
	}
	return g.Fields
}

func (g *GetRelationsV2Request) GetFrom() *int64 {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetRelationsV2Request) GetHydrate() *bool {
	if g == nil {
		return nil
	}
	return g.Hydrate
}

func (g *GetRelationsV2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRelationsV2Request) GetIncludeReverse() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeReverse
}

func (g *GetRelationsV2Request) GetQuery() *string {
	if g == nil {
		return nil
	}
	return g.Query
}

func (g *GetRelationsV2Request) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetRelationsV2Request) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

// GetRelationsV2ResponseBody - A generic error returned by the API
type GetRelationsV2ResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetRelationsV2ResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetRelationsV2ResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetRelationsV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	GetRelationsRespWithPagination *shared.GetRelationsRespWithPagination
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *GetRelationsV2ResponseBody
}

func (g *GetRelationsV2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRelationsV2Response) GetGetRelationsRespWithPagination() *shared.GetRelationsRespWithPagination {
	if g == nil {
		return nil
	}
	return g.GetRelationsRespWithPagination
}

func (g *GetRelationsV2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRelationsV2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRelationsV2Response) GetObject() *GetRelationsV2ResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
