// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type GetRelationsRequest struct {
	// Filter results to exclude schemas
	ExcludeSchemas []string `queryParam:"style=form,explode=false,name=exclude_schemas"`
	// Starting page number
	From *int64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	// When true, enables entity hydration to resolve nested $relation & $relation_ref references in-place.
	Hydrate *bool `default:"false" queryParam:"style=form,explode=true,name=hydrate"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// When true, includes reverse relations in response (other entities pointing to this entity)
	IncludeReverse *bool `default:"false" queryParam:"style=form,explode=true,name=include_reverse"`
	// Filter results to only include schemas
	IncludeSchemas []string `queryParam:"style=form,explode=false,name=include_schemas"`
	// Number of results to return per page
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (g GetRelationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRelationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id", "slug"}); err != nil {
		return err
	}
	return nil
}

func (g *GetRelationsRequest) GetExcludeSchemas() []string {
	if g == nil {
		return nil
	}
	return g.ExcludeSchemas
}

func (g *GetRelationsRequest) GetFrom() *int64 {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetRelationsRequest) GetHydrate() *bool {
	if g == nil {
		return nil
	}
	return g.Hydrate
}

func (g *GetRelationsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRelationsRequest) GetIncludeReverse() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeReverse
}

func (g *GetRelationsRequest) GetIncludeSchemas() []string {
	if g == nil {
		return nil
	}
	return g.IncludeSchemas
}

func (g *GetRelationsRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetRelationsRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

// GetRelationsResponseBody - A generic error returned by the API
type GetRelationsResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetRelationsResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetRelationsResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetRelationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	GetRelationsResp []shared.GetRelationsResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *GetRelationsResponseBody
}

func (g *GetRelationsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRelationsResponse) GetGetRelationsResp() []shared.GetRelationsResp {
	if g == nil {
		return nil
	}
	return g.GetRelationsResp
}

func (g *GetRelationsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRelationsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRelationsResponse) GetObject() *GetRelationsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
