// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type GetTaxonomyClassificationRequest struct {
	// Taxonomy Classification slug
	ClassificationSlug string `pathParam:"style=simple,explode=false,name=classificationSlug"`
}

func (o *GetTaxonomyClassificationRequest) GetClassificationSlug() string {
	if o == nil {
		return ""
	}
	return o.ClassificationSlug
}

type GetTaxonomyClassificationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Taxonomy classification
	TaxonomyClassification *shared.TaxonomyClassification
}

func (o *GetTaxonomyClassificationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTaxonomyClassificationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTaxonomyClassificationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTaxonomyClassificationResponse) GetTaxonomyClassification() *shared.TaxonomyClassification {
	if o == nil {
		return nil
	}
	return o.TaxonomyClassification
}
