// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type GetTaxonomyClassificationRequest struct {
	// Taxonomy Classification slug
	ClassificationSlug string `pathParam:"style=simple,explode=false,name=classificationSlug"`
}

func (o *GetTaxonomyClassificationRequest) GetClassificationSlug() string {
	if o == nil {
		return ""
	}
	return o.ClassificationSlug
}

// GetTaxonomyClassificationResponseBody - A generic error returned by the API
type GetTaxonomyClassificationResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *GetTaxonomyClassificationResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetTaxonomyClassificationResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetTaxonomyClassificationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Taxonomy classification
	TaxonomyClassification *shared.TaxonomyClassification
	// The requested resource was not found
	Object *GetTaxonomyClassificationResponseBody
}

func (o *GetTaxonomyClassificationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTaxonomyClassificationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTaxonomyClassificationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTaxonomyClassificationResponse) GetTaxonomyClassification() *shared.TaxonomyClassification {
	if o == nil {
		return nil
	}
	return o.TaxonomyClassification
}

func (o *GetTaxonomyClassificationResponse) GetObject() *GetTaxonomyClassificationResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
