// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type ListSchemasV2Request struct {
	// List of schema slugs to exclude from the results. Accepts a comma-separated list of slugs to exclude from the results.
	Exclude []string `queryParam:"style=form,explode=false,name=exclude"`
	// Return full schemas including all attributes and capabilities
	Full *bool `default:"false" queryParam:"style=form,explode=true,name=full"`
	// List of schema slugs to include in the results. When provided, only these schemas are returned. Accepts a comma-separated list of slugs.
	Include []string `queryParam:"style=form,explode=false,name=include"`
	// When true, return the latest version instead of the frozen version for frozen schemas.
	Latest *bool `default:"false" queryParam:"style=form,explode=true,name=latest"`
	// Return unpublished draft schemas
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Unpublished *bool `default:"false" queryParam:"style=form,explode=true,name=unpublished"`
}

func (l ListSchemasV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSchemasV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSchemasV2Request) GetExclude() []string {
	if l == nil {
		return nil
	}
	return l.Exclude
}

func (l *ListSchemasV2Request) GetFull() *bool {
	if l == nil {
		return nil
	}
	return l.Full
}

func (l *ListSchemasV2Request) GetInclude() []string {
	if l == nil {
		return nil
	}
	return l.Include
}

func (l *ListSchemasV2Request) GetLatest() *bool {
	if l == nil {
		return nil
	}
	return l.Latest
}

func (l *ListSchemasV2Request) GetUnpublished() *bool {
	if l == nil {
		return nil
	}
	return l.Unpublished
}

// #region class-body-listschemasv2request
// #endregion class-body-listschemasv2request

// ListSchemasV2ResponseBody - Success
type ListSchemasV2ResponseBody struct {
	Results []shared.EntitySchemaItem `json:"results,omitempty"`
}

func (l *ListSchemasV2ResponseBody) GetResults() []shared.EntitySchemaItem {
	if l == nil {
		return nil
	}
	return l.Results
}

// #region class-body-listschemasv2responsebody
// #endregion class-body-listschemasv2responsebody

type ListSchemasV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *ListSchemasV2ResponseBody
}

func (l *ListSchemasV2Response) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListSchemasV2Response) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListSchemasV2Response) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListSchemasV2Response) GetObject() *ListSchemasV2ResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

// #region class-body-listschemasv2response
// #endregion class-body-listschemasv2response
