// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

// ListSchemaBlueprintsResponseBody - Success
type ListSchemaBlueprintsResponseBody struct {
	Results []shared.EntitySchemaItem `json:"results,omitempty"`
}

func (l *ListSchemaBlueprintsResponseBody) GetResults() []shared.EntitySchemaItem {
	if l == nil {
		return nil
	}
	return l.Results
}

type ListSchemaBlueprintsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *ListSchemaBlueprintsResponseBody
}

func (l *ListSchemaBlueprintsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListSchemaBlueprintsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListSchemaBlueprintsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListSchemaBlueprintsResponse) GetObject() *ListSchemaBlueprintsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
