// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// ListFavoriteViewsForUserResults - A saved entity view
type ListFavoriteViewsForUserResults struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// Generated uuid for a saved view
	ID        *string `json:"id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (o *ListFavoriteViewsForUserResults) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *ListFavoriteViewsForUserResults) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ListFavoriteViewsForUserResults) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

// ListFavoriteViewsForUserResponseBody - Success
type ListFavoriteViewsForUserResponseBody struct {
	Results []ListFavoriteViewsForUserResults `json:"results,omitempty"`
}

func (o *ListFavoriteViewsForUserResponseBody) GetResults() []ListFavoriteViewsForUserResults {
	if o == nil {
		return nil
	}
	return o.Results
}

type ListFavoriteViewsForUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *ListFavoriteViewsForUserResponseBody
}

func (o *ListFavoriteViewsForUserResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListFavoriteViewsForUserResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListFavoriteViewsForUserResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListFavoriteViewsForUserResponse) GetObject() *ListFavoriteViewsForUserResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
