// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type ListTaxonomyClassificationsForSchemaRequest struct {
	Query *string  `queryParam:"style=form,explode=true,name=query"`
	Size  *float64 `queryParam:"style=form,explode=true,name=size"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
	// Taxonomy slug
	TaxonomySlug string `pathParam:"style=simple,explode=false,name=taxonomySlug"`
}

func (l *ListTaxonomyClassificationsForSchemaRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListTaxonomyClassificationsForSchemaRequest) GetSize() *float64 {
	if l == nil {
		return nil
	}
	return l.Size
}

func (l *ListTaxonomyClassificationsForSchemaRequest) GetSlug() string {
	if l == nil {
		return ""
	}
	return l.Slug
}

func (l *ListTaxonomyClassificationsForSchemaRequest) GetTaxonomySlug() string {
	if l == nil {
		return ""
	}
	return l.TaxonomySlug
}

// ListTaxonomyClassificationsForSchemaResponseBody - List of taxonomy classifications
type ListTaxonomyClassificationsForSchemaResponseBody struct {
	Results []shared.TaxonomyClassification `json:"results,omitempty"`
}

func (l *ListTaxonomyClassificationsForSchemaResponseBody) GetResults() []shared.TaxonomyClassification {
	if l == nil {
		return nil
	}
	return l.Results
}

type ListTaxonomyClassificationsForSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of taxonomy classifications
	Object *ListTaxonomyClassificationsForSchemaResponseBody
}

func (l *ListTaxonomyClassificationsForSchemaResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListTaxonomyClassificationsForSchemaResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListTaxonomyClassificationsForSchemaResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListTaxonomyClassificationsForSchemaResponse) GetObject() *ListTaxonomyClassificationsForSchemaResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
