// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type PatchSavedViewRequest struct {
	SavedViewPartial *shared.SavedViewPartial `request:"mediaType=application/json"`
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PatchSavedViewRequest) GetSavedViewPartial() *shared.SavedViewPartial {
	if o == nil {
		return nil
	}
	return o.SavedViewPartial
}

func (o *PatchSavedViewRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// PatchSavedViewResponseBody - A saved entity view
type PatchSavedViewResponseBody struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// Generated uuid for a saved view
	ID        *string `json:"id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (o *PatchSavedViewResponseBody) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *PatchSavedViewResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PatchSavedViewResponseBody) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

type PatchSavedViewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *PatchSavedViewResponseBody
}

func (o *PatchSavedViewResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchSavedViewResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchSavedViewResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchSavedViewResponse) GetObject() *PatchSavedViewResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
