// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type PutSchemaGroupRequest struct {
	EntitySchemaGroupWithCompositeID *shared.EntitySchemaGroupWithCompositeIDInput `request:"mediaType=application/json"`
	// Schema Slug and the Group ID
	CompositeID string `pathParam:"style=simple,explode=false,name=composite_id"`
}

func (p *PutSchemaGroupRequest) GetEntitySchemaGroupWithCompositeID() *shared.EntitySchemaGroupWithCompositeIDInput {
	if p == nil {
		return nil
	}
	return p.EntitySchemaGroupWithCompositeID
}

func (p *PutSchemaGroupRequest) GetCompositeID() string {
	if p == nil {
		return ""
	}
	return p.CompositeID
}

type PutSchemaGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	EntitySchemaGroupWithCompositeID *shared.EntitySchemaGroupWithCompositeID
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PutSchemaGroupResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutSchemaGroupResponse) GetEntitySchemaGroupWithCompositeID() *shared.EntitySchemaGroupWithCompositeID {
	if p == nil {
		return nil
	}
	return p.EntitySchemaGroupWithCompositeID
}

func (p *PutSchemaGroupResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutSchemaGroupResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
