// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type PutSchemaRequest struct {
	EntitySchema *shared.EntitySchema `request:"mediaType=application/json"`
	Draft        *bool                `default:"false" queryParam:"style=form,explode=true,name=draft"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (p PutSchemaRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutSchemaRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PutSchemaRequest) GetEntitySchema() *shared.EntitySchema {
	if o == nil {
		return nil
	}
	return o.EntitySchema
}

func (o *PutSchemaRequest) GetDraft() *bool {
	if o == nil {
		return nil
	}
	return o.Draft
}

func (o *PutSchemaRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type PutSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	EntitySchemaItem *shared.EntitySchemaItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutSchemaResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutSchemaResponse) GetEntitySchemaItem() *shared.EntitySchemaItem {
	if o == nil {
		return nil
	}
	return o.EntitySchemaItem
}

func (o *PutSchemaResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutSchemaResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
