// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

// ReindexEntityRequestBody - This endpoint doesn't require a payload, but an empty object can be sent to satisfy certain HTTP clients.
type ReindexEntityRequestBody struct {
}

type ReindexEntityRequest struct {
	RequestBody *ReindexEntityRequestBody `request:"mediaType=application/json"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *ReindexEntityRequest) GetRequestBody() *ReindexEntityRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *ReindexEntityRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ReindexEntityRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type ReindexEntityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The reindexed entity
	EntityItem *shared.EntityItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReindexEntityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReindexEntityResponse) GetEntityItem() *shared.EntityItem {
	if o == nil {
		return nil
	}
	return o.EntityItem
}

func (o *ReindexEntityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReindexEntityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
