// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// UpdateSavedViewRequestBody - A saved entity view
type UpdateSavedViewRequestBody struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// Generated uuid for a saved view
	ID        *string `json:"id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (o *UpdateSavedViewRequestBody) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UpdateSavedViewRequestBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UpdateSavedViewRequestBody) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

type UpdateSavedViewRequest struct {
	RequestBody *UpdateSavedViewRequestBody `request:"mediaType=application/json"`
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateSavedViewRequest) GetRequestBody() *UpdateSavedViewRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *UpdateSavedViewRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// UpdateSavedViewResponseBody - A saved entity view
type UpdateSavedViewResponseBody struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// Generated uuid for a saved view
	ID        *string `json:"id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (o *UpdateSavedViewResponseBody) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UpdateSavedViewResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UpdateSavedViewResponseBody) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

type UpdateSavedViewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *UpdateSavedViewResponseBody
}

func (o *UpdateSavedViewResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateSavedViewResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateSavedViewResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateSavedViewResponse) GetObject() *UpdateSavedViewResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
