// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type ValidateEntityRequest struct {
	Entity *shared.EntityInput `request:"mediaType=application/json"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *ValidateEntityRequest) GetEntity() *shared.EntityInput {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *ValidateEntityRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type ValidateEntityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Error
	EntityValidationResultError *shared.EntityValidationResultError
	// Success
	EntityValidationResultSuccess *shared.EntityValidationResultSuccess
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ValidateEntityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ValidateEntityResponse) GetEntityValidationResultError() *shared.EntityValidationResultError {
	if o == nil {
		return nil
	}
	return o.EntityValidationResultError
}

func (o *ValidateEntityResponse) GetEntityValidationResultSuccess() *shared.EntityValidationResultSuccess {
	if o == nil {
		return nil
	}
	return o.EntityValidationResultSuccess
}

func (o *ValidateEntityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ValidateEntityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
