// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type ValidateEntityV2Request struct {
	Entity *shared.EntityInput `request:"mediaType=application/json"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *ValidateEntityV2Request) GetEntity() *shared.EntityInput {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *ValidateEntityV2Request) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// ValidateEntityV2ResponseBody - A generic error returned by the API
type ValidateEntityV2ResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *ValidateEntityV2ResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ValidateEntityV2ResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type ValidateEntityV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Error
	EntityValidationV2ResultError *shared.EntityValidationV2ResultError
	// Success
	EntityValidationV2ResultSuccess *shared.EntityValidationV2ResultSuccess
	Headers                         map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Too many requests
	Object *ValidateEntityV2ResponseBody
}

func (o *ValidateEntityV2Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ValidateEntityV2Response) GetEntityValidationV2ResultError() *shared.EntityValidationV2ResultError {
	if o == nil {
		return nil
	}
	return o.EntityValidationV2ResultError
}

func (o *ValidateEntityV2Response) GetEntityValidationV2ResultSuccess() *shared.EntityValidationV2ResultSuccess {
	if o == nil {
		return nil
	}
	return o.EntityValidationV2ResultSuccess
}

func (o *ValidateEntityV2Response) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *ValidateEntityV2Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ValidateEntityV2Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ValidateEntityV2Response) GetObject() *ValidateEntityV2ResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
