// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"net/http"
)

type ValidateEntityRequest struct {
	Entity *shared.EntityInput `request:"mediaType=application/json"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (v *ValidateEntityRequest) GetEntity() *shared.EntityInput {
	if v == nil {
		return nil
	}
	return v.Entity
}

func (v *ValidateEntityRequest) GetSlug() string {
	if v == nil {
		return ""
	}
	return v.Slug
}

// ValidateEntityResponseBody - A generic error returned by the API
type ValidateEntityResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (v *ValidateEntityResponseBody) GetError() *string {
	if v == nil {
		return nil
	}
	return v.Error
}

func (v *ValidateEntityResponseBody) GetStatus() *int64 {
	if v == nil {
		return nil
	}
	return v.Status
}

type ValidateEntityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Error
	EntityValidationResultError *shared.EntityValidationResultError
	// Success
	EntityValidationResultSuccess *shared.EntityValidationResultSuccess
	Headers                       map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Too many requests
	Object *ValidateEntityResponseBody
}

func (v *ValidateEntityResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *ValidateEntityResponse) GetEntityValidationResultError() *shared.EntityValidationResultError {
	if v == nil {
		return nil
	}
	return v.EntityValidationResultError
}

func (v *ValidateEntityResponse) GetEntityValidationResultSuccess() *shared.EntityValidationResultSuccess {
	if v == nil {
		return nil
	}
	return v.EntityValidationResultSuccess
}

func (v *ValidateEntityResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

func (v *ValidateEntityResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *ValidateEntityResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *ValidateEntityResponse) GetObject() *ValidateEntityResponseBody {
	if v == nil {
		return nil
	}
	return v.Object
}
