// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type WipeAllEntitiesRequestBody struct {
	Schemas []string `json:"schemas,omitempty"`
}

func (w *WipeAllEntitiesRequestBody) GetSchemas() []string {
	if w == nil {
		return nil
	}
	return w.Schemas
}

type WipeAllEntitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (w *WipeAllEntitiesResponse) GetContentType() string {
	if w == nil {
		return ""
	}
	return w.ContentType
}

func (w *WipeAllEntitiesResponse) GetStatusCode() int {
	if w == nil {
		return 0
	}
	return w.StatusCode
}

func (w *WipeAllEntitiesResponse) GetRawResponse() *http.Response {
	if w == nil {
		return nil
	}
	return w.RawResponse
}
