// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"time"
)

type ActivityItem struct {
	// See https://github.com/ulid/spec
	ID     *string                `json:"_id,omitempty"`
	Caller *ActivityCallerContext `json:"caller,omitempty"`
	// Message for activity. Supports handlebars syntax.
	Message    string            `json:"message"`
	Operations []EntityOperation `json:"operations,omitempty"`
	// Count of total operations attached to this activity
	OperationsTotal *int64         `json:"operations_total,omitempty"`
	Payload         map[string]any `json:"payload,omitempty"`
	// Indicates whether the activity is in the pending state.
	// Pending activities are not yet visible in the activity feed and events are not yet dispatched.
	//
	Pending   *bool      `default:"false" json:"pending"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Title for activity. Supports handlebars syntax.
	Title string `json:"title"`
	Type  string `json:"type"`
}

func (a ActivityItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivityItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"message", "title", "type"}); err != nil {
		return err
	}
	return nil
}

func (a *ActivityItem) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *ActivityItem) GetCaller() *ActivityCallerContext {
	if a == nil {
		return nil
	}
	return a.Caller
}

func (a *ActivityItem) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *ActivityItem) GetOperations() []EntityOperation {
	if a == nil {
		return nil
	}
	return a.Operations
}

func (a *ActivityItem) GetOperationsTotal() *int64 {
	if a == nil {
		return nil
	}
	return a.OperationsTotal
}

func (a *ActivityItem) GetPayload() map[string]any {
	if a == nil {
		return nil
	}
	return a.Payload
}

func (a *ActivityItem) GetPending() *bool {
	if a == nil {
		return nil
	}
	return a.Pending
}

func (a *ActivityItem) GetTimestamp() *time.Time {
	if a == nil {
		return nil
	}
	return a.Timestamp
}

func (a *ActivityItem) GetTitle() string {
	if a == nil {
		return ""
	}
	return a.Title
}

func (a *ActivityItem) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}
