// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

type AttributeType string

const (
	AttributeTypeTextAttribute                  AttributeType = "TextAttribute"
	AttributeTypeLinkAttribute                  AttributeType = "LinkAttribute"
	AttributeTypeDateAttribute                  AttributeType = "DateAttribute"
	AttributeTypeCountryAttribute               AttributeType = "CountryAttribute"
	AttributeTypeBooleanAttribute               AttributeType = "BooleanAttribute"
	AttributeTypeSelectAttribute                AttributeType = "SelectAttribute"
	AttributeTypeMultiSelectAttribute           AttributeType = "MultiSelectAttribute"
	AttributeTypeStatusAttribute                AttributeType = "StatusAttribute"
	AttributeTypeSequenceAttribute              AttributeType = "SequenceAttribute"
	AttributeTypeRelationAttribute              AttributeType = "RelationAttribute"
	AttributeTypeUserRelationAttribute          AttributeType = "UserRelationAttribute"
	AttributeTypeAddressAttribute               AttributeType = "AddressAttribute"
	AttributeTypeAddressRelationAttribute       AttributeType = "AddressRelationAttribute"
	AttributeTypePaymentMethodRelationAttribute AttributeType = "PaymentMethodRelationAttribute"
	AttributeTypeCurrencyAttribute              AttributeType = "CurrencyAttribute"
	AttributeTypeTagsAttribute                  AttributeType = "TagsAttribute"
	AttributeTypeMessageEmailAddressAttribute   AttributeType = "MessageEmailAddressAttribute"
	AttributeTypeNumberAttribute                AttributeType = "NumberAttribute"
	AttributeTypeConsentAttribute               AttributeType = "ConsentAttribute"
	AttributeTypeInternalAttribute              AttributeType = "InternalAttribute"
	AttributeTypeOrderedListAttribute           AttributeType = "OrderedListAttribute"
	AttributeTypeFileAttribute                  AttributeType = "FileAttribute"
	AttributeTypeComputedAttribute              AttributeType = "ComputedAttribute"
	AttributeTypePartnerStatusAttribute         AttributeType = "PartnerStatusAttribute"
	AttributeTypeInvitationEmailAttribute       AttributeType = "InvitationEmailAttribute"
	AttributeTypeAutomationAttribute            AttributeType = "AutomationAttribute"
	AttributeTypeInternalUserAttribute          AttributeType = "InternalUserAttribute"
	AttributeTypePurposeAttribute               AttributeType = "PurposeAttribute"
	AttributeTypePartnerOrganisationAttribute   AttributeType = "PartnerOrganisationAttribute"
	AttributeTypePortalAccessAttribute          AttributeType = "PortalAccessAttribute"
	AttributeTypePhoneAttribute                 AttributeType = "PhoneAttribute"
	AttributeTypeEmailAttribute                 AttributeType = "EmailAttribute"
	AttributeTypePaymentAttribute               AttributeType = "PaymentAttribute"
	AttributeTypePriceComponentAttribute        AttributeType = "PriceComponentAttribute"
)

type Attribute struct {
	TextAttribute                  *TextAttribute                  `queryParam:"inline,name=Attribute"`
	LinkAttribute                  *LinkAttribute                  `queryParam:"inline,name=Attribute"`
	DateAttribute                  *DateAttribute                  `queryParam:"inline,name=Attribute"`
	CountryAttribute               *CountryAttribute               `queryParam:"inline,name=Attribute"`
	BooleanAttribute               *BooleanAttribute               `queryParam:"inline,name=Attribute"`
	SelectAttribute                *SelectAttribute                `queryParam:"inline,name=Attribute"`
	MultiSelectAttribute           *MultiSelectAttribute           `queryParam:"inline,name=Attribute"`
	StatusAttribute                *StatusAttribute                `queryParam:"inline,name=Attribute"`
	SequenceAttribute              *SequenceAttribute              `queryParam:"inline,name=Attribute"`
	RelationAttribute              *RelationAttribute              `queryParam:"inline,name=Attribute"`
	UserRelationAttribute          *UserRelationAttribute          `queryParam:"inline,name=Attribute"`
	AddressAttribute               *AddressAttribute               `queryParam:"inline,name=Attribute"`
	AddressRelationAttribute       *AddressRelationAttribute       `queryParam:"inline,name=Attribute"`
	PaymentMethodRelationAttribute *PaymentMethodRelationAttribute `queryParam:"inline,name=Attribute"`
	CurrencyAttribute              *CurrencyAttribute              `queryParam:"inline,name=Attribute"`
	TagsAttribute                  *TagsAttribute                  `queryParam:"inline,name=Attribute"`
	MessageEmailAddressAttribute   *MessageEmailAddressAttribute   `queryParam:"inline,name=Attribute"`
	NumberAttribute                *NumberAttribute                `queryParam:"inline,name=Attribute"`
	ConsentAttribute               *ConsentAttribute               `queryParam:"inline,name=Attribute"`
	InternalAttribute              *InternalAttribute              `queryParam:"inline,name=Attribute"`
	OrderedListAttribute           *OrderedListAttribute           `queryParam:"inline,name=Attribute"`
	FileAttribute                  *FileAttribute                  `queryParam:"inline,name=Attribute"`
	ComputedAttribute              *ComputedAttribute              `queryParam:"inline,name=Attribute"`
	PartnerStatusAttribute         *PartnerStatusAttribute         `queryParam:"inline,name=Attribute"`
	InvitationEmailAttribute       *InvitationEmailAttribute       `queryParam:"inline,name=Attribute"`
	AutomationAttribute            *AutomationAttribute            `queryParam:"inline,name=Attribute"`
	InternalUserAttribute          *InternalUserAttribute          `queryParam:"inline,name=Attribute"`
	PurposeAttribute               *PurposeAttribute               `queryParam:"inline,name=Attribute"`
	PartnerOrganisationAttribute   *PartnerOrganisationAttribute   `queryParam:"inline,name=Attribute"`
	PortalAccessAttribute          *PortalAccessAttribute          `queryParam:"inline,name=Attribute"`
	PhoneAttribute                 *PhoneAttribute                 `queryParam:"inline,name=Attribute"`
	EmailAttribute                 *EmailAttribute                 `queryParam:"inline,name=Attribute"`
	PaymentAttribute               *PaymentAttribute               `queryParam:"inline,name=Attribute"`
	PriceComponentAttribute        *PriceComponentAttribute        `queryParam:"inline,name=Attribute"`

	Type AttributeType
}

func CreateAttributeTextAttribute(textAttribute TextAttribute) Attribute {
	typ := AttributeTypeTextAttribute

	return Attribute{
		TextAttribute: &textAttribute,
		Type:          typ,
	}
}

func CreateAttributeLinkAttribute(linkAttribute LinkAttribute) Attribute {
	typ := AttributeTypeLinkAttribute

	return Attribute{
		LinkAttribute: &linkAttribute,
		Type:          typ,
	}
}

func CreateAttributeDateAttribute(dateAttribute DateAttribute) Attribute {
	typ := AttributeTypeDateAttribute

	return Attribute{
		DateAttribute: &dateAttribute,
		Type:          typ,
	}
}

func CreateAttributeCountryAttribute(countryAttribute CountryAttribute) Attribute {
	typ := AttributeTypeCountryAttribute

	return Attribute{
		CountryAttribute: &countryAttribute,
		Type:             typ,
	}
}

func CreateAttributeBooleanAttribute(booleanAttribute BooleanAttribute) Attribute {
	typ := AttributeTypeBooleanAttribute

	return Attribute{
		BooleanAttribute: &booleanAttribute,
		Type:             typ,
	}
}

func CreateAttributeSelectAttribute(selectAttribute SelectAttribute) Attribute {
	typ := AttributeTypeSelectAttribute

	return Attribute{
		SelectAttribute: &selectAttribute,
		Type:            typ,
	}
}

func CreateAttributeMultiSelectAttribute(multiSelectAttribute MultiSelectAttribute) Attribute {
	typ := AttributeTypeMultiSelectAttribute

	return Attribute{
		MultiSelectAttribute: &multiSelectAttribute,
		Type:                 typ,
	}
}

func CreateAttributeStatusAttribute(statusAttribute StatusAttribute) Attribute {
	typ := AttributeTypeStatusAttribute

	return Attribute{
		StatusAttribute: &statusAttribute,
		Type:            typ,
	}
}

func CreateAttributeSequenceAttribute(sequenceAttribute SequenceAttribute) Attribute {
	typ := AttributeTypeSequenceAttribute

	return Attribute{
		SequenceAttribute: &sequenceAttribute,
		Type:              typ,
	}
}

func CreateAttributeRelationAttribute(relationAttribute RelationAttribute) Attribute {
	typ := AttributeTypeRelationAttribute

	return Attribute{
		RelationAttribute: &relationAttribute,
		Type:              typ,
	}
}

func CreateAttributeUserRelationAttribute(userRelationAttribute UserRelationAttribute) Attribute {
	typ := AttributeTypeUserRelationAttribute

	return Attribute{
		UserRelationAttribute: &userRelationAttribute,
		Type:                  typ,
	}
}

func CreateAttributeAddressAttribute(addressAttribute AddressAttribute) Attribute {
	typ := AttributeTypeAddressAttribute

	return Attribute{
		AddressAttribute: &addressAttribute,
		Type:             typ,
	}
}

func CreateAttributeAddressRelationAttribute(addressRelationAttribute AddressRelationAttribute) Attribute {
	typ := AttributeTypeAddressRelationAttribute

	return Attribute{
		AddressRelationAttribute: &addressRelationAttribute,
		Type:                     typ,
	}
}

func CreateAttributePaymentMethodRelationAttribute(paymentMethodRelationAttribute PaymentMethodRelationAttribute) Attribute {
	typ := AttributeTypePaymentMethodRelationAttribute

	return Attribute{
		PaymentMethodRelationAttribute: &paymentMethodRelationAttribute,
		Type:                           typ,
	}
}

func CreateAttributeCurrencyAttribute(currencyAttribute CurrencyAttribute) Attribute {
	typ := AttributeTypeCurrencyAttribute

	return Attribute{
		CurrencyAttribute: &currencyAttribute,
		Type:              typ,
	}
}

func CreateAttributeTagsAttribute(tagsAttribute TagsAttribute) Attribute {
	typ := AttributeTypeTagsAttribute

	return Attribute{
		TagsAttribute: &tagsAttribute,
		Type:          typ,
	}
}

func CreateAttributeMessageEmailAddressAttribute(messageEmailAddressAttribute MessageEmailAddressAttribute) Attribute {
	typ := AttributeTypeMessageEmailAddressAttribute

	return Attribute{
		MessageEmailAddressAttribute: &messageEmailAddressAttribute,
		Type:                         typ,
	}
}

func CreateAttributeNumberAttribute(numberAttribute NumberAttribute) Attribute {
	typ := AttributeTypeNumberAttribute

	return Attribute{
		NumberAttribute: &numberAttribute,
		Type:            typ,
	}
}

func CreateAttributeConsentAttribute(consentAttribute ConsentAttribute) Attribute {
	typ := AttributeTypeConsentAttribute

	return Attribute{
		ConsentAttribute: &consentAttribute,
		Type:             typ,
	}
}

func CreateAttributeInternalAttribute(internalAttribute InternalAttribute) Attribute {
	typ := AttributeTypeInternalAttribute

	return Attribute{
		InternalAttribute: &internalAttribute,
		Type:              typ,
	}
}

func CreateAttributeOrderedListAttribute(orderedListAttribute OrderedListAttribute) Attribute {
	typ := AttributeTypeOrderedListAttribute

	return Attribute{
		OrderedListAttribute: &orderedListAttribute,
		Type:                 typ,
	}
}

func CreateAttributeFileAttribute(fileAttribute FileAttribute) Attribute {
	typ := AttributeTypeFileAttribute

	return Attribute{
		FileAttribute: &fileAttribute,
		Type:          typ,
	}
}

func CreateAttributeComputedAttribute(computedAttribute ComputedAttribute) Attribute {
	typ := AttributeTypeComputedAttribute

	return Attribute{
		ComputedAttribute: &computedAttribute,
		Type:              typ,
	}
}

func CreateAttributePartnerStatusAttribute(partnerStatusAttribute PartnerStatusAttribute) Attribute {
	typ := AttributeTypePartnerStatusAttribute

	return Attribute{
		PartnerStatusAttribute: &partnerStatusAttribute,
		Type:                   typ,
	}
}

func CreateAttributeInvitationEmailAttribute(invitationEmailAttribute InvitationEmailAttribute) Attribute {
	typ := AttributeTypeInvitationEmailAttribute

	return Attribute{
		InvitationEmailAttribute: &invitationEmailAttribute,
		Type:                     typ,
	}
}

func CreateAttributeAutomationAttribute(automationAttribute AutomationAttribute) Attribute {
	typ := AttributeTypeAutomationAttribute

	return Attribute{
		AutomationAttribute: &automationAttribute,
		Type:                typ,
	}
}

func CreateAttributeInternalUserAttribute(internalUserAttribute InternalUserAttribute) Attribute {
	typ := AttributeTypeInternalUserAttribute

	return Attribute{
		InternalUserAttribute: &internalUserAttribute,
		Type:                  typ,
	}
}

func CreateAttributePurposeAttribute(purposeAttribute PurposeAttribute) Attribute {
	typ := AttributeTypePurposeAttribute

	return Attribute{
		PurposeAttribute: &purposeAttribute,
		Type:             typ,
	}
}

func CreateAttributePartnerOrganisationAttribute(partnerOrganisationAttribute PartnerOrganisationAttribute) Attribute {
	typ := AttributeTypePartnerOrganisationAttribute

	return Attribute{
		PartnerOrganisationAttribute: &partnerOrganisationAttribute,
		Type:                         typ,
	}
}

func CreateAttributePortalAccessAttribute(portalAccessAttribute PortalAccessAttribute) Attribute {
	typ := AttributeTypePortalAccessAttribute

	return Attribute{
		PortalAccessAttribute: &portalAccessAttribute,
		Type:                  typ,
	}
}

func CreateAttributePhoneAttribute(phoneAttribute PhoneAttribute) Attribute {
	typ := AttributeTypePhoneAttribute

	return Attribute{
		PhoneAttribute: &phoneAttribute,
		Type:           typ,
	}
}

func CreateAttributeEmailAttribute(emailAttribute EmailAttribute) Attribute {
	typ := AttributeTypeEmailAttribute

	return Attribute{
		EmailAttribute: &emailAttribute,
		Type:           typ,
	}
}

func CreateAttributePaymentAttribute(paymentAttribute PaymentAttribute) Attribute {
	typ := AttributeTypePaymentAttribute

	return Attribute{
		PaymentAttribute: &paymentAttribute,
		Type:             typ,
	}
}

func CreateAttributePriceComponentAttribute(priceComponentAttribute PriceComponentAttribute) Attribute {
	typ := AttributeTypePriceComponentAttribute

	return Attribute{
		PriceComponentAttribute: &priceComponentAttribute,
		Type:                    typ,
	}
}

func (u *Attribute) UnmarshalJSON(data []byte) error {

	var currencyAttribute CurrencyAttribute = CurrencyAttribute{}
	if err := utils.UnmarshalJSON(data, &currencyAttribute, "", true, nil); err == nil {
		u.CurrencyAttribute = &currencyAttribute
		u.Type = AttributeTypeCurrencyAttribute
		return nil
	}

	var consentAttribute ConsentAttribute = ConsentAttribute{}
	if err := utils.UnmarshalJSON(data, &consentAttribute, "", true, nil); err == nil {
		u.ConsentAttribute = &consentAttribute
		u.Type = AttributeTypeConsentAttribute
		return nil
	}

	var computedAttribute ComputedAttribute = ComputedAttribute{}
	if err := utils.UnmarshalJSON(data, &computedAttribute, "", true, nil); err == nil {
		u.ComputedAttribute = &computedAttribute
		u.Type = AttributeTypeComputedAttribute
		return nil
	}

	var textAttribute TextAttribute = TextAttribute{}
	if err := utils.UnmarshalJSON(data, &textAttribute, "", true, nil); err == nil {
		u.TextAttribute = &textAttribute
		u.Type = AttributeTypeTextAttribute
		return nil
	}

	var linkAttribute LinkAttribute = LinkAttribute{}
	if err := utils.UnmarshalJSON(data, &linkAttribute, "", true, nil); err == nil {
		u.LinkAttribute = &linkAttribute
		u.Type = AttributeTypeLinkAttribute
		return nil
	}

	var dateAttribute DateAttribute = DateAttribute{}
	if err := utils.UnmarshalJSON(data, &dateAttribute, "", true, nil); err == nil {
		u.DateAttribute = &dateAttribute
		u.Type = AttributeTypeDateAttribute
		return nil
	}

	var countryAttribute CountryAttribute = CountryAttribute{}
	if err := utils.UnmarshalJSON(data, &countryAttribute, "", true, nil); err == nil {
		u.CountryAttribute = &countryAttribute
		u.Type = AttributeTypeCountryAttribute
		return nil
	}

	var booleanAttribute BooleanAttribute = BooleanAttribute{}
	if err := utils.UnmarshalJSON(data, &booleanAttribute, "", true, nil); err == nil {
		u.BooleanAttribute = &booleanAttribute
		u.Type = AttributeTypeBooleanAttribute
		return nil
	}

	var selectAttribute SelectAttribute = SelectAttribute{}
	if err := utils.UnmarshalJSON(data, &selectAttribute, "", true, nil); err == nil {
		u.SelectAttribute = &selectAttribute
		u.Type = AttributeTypeSelectAttribute
		return nil
	}

	var multiSelectAttribute MultiSelectAttribute = MultiSelectAttribute{}
	if err := utils.UnmarshalJSON(data, &multiSelectAttribute, "", true, nil); err == nil {
		u.MultiSelectAttribute = &multiSelectAttribute
		u.Type = AttributeTypeMultiSelectAttribute
		return nil
	}

	var statusAttribute StatusAttribute = StatusAttribute{}
	if err := utils.UnmarshalJSON(data, &statusAttribute, "", true, nil); err == nil {
		u.StatusAttribute = &statusAttribute
		u.Type = AttributeTypeStatusAttribute
		return nil
	}

	var sequenceAttribute SequenceAttribute = SequenceAttribute{}
	if err := utils.UnmarshalJSON(data, &sequenceAttribute, "", true, nil); err == nil {
		u.SequenceAttribute = &sequenceAttribute
		u.Type = AttributeTypeSequenceAttribute
		return nil
	}

	var relationAttribute RelationAttribute = RelationAttribute{}
	if err := utils.UnmarshalJSON(data, &relationAttribute, "", true, nil); err == nil {
		u.RelationAttribute = &relationAttribute
		u.Type = AttributeTypeRelationAttribute
		return nil
	}

	var userRelationAttribute UserRelationAttribute = UserRelationAttribute{}
	if err := utils.UnmarshalJSON(data, &userRelationAttribute, "", true, nil); err == nil {
		u.UserRelationAttribute = &userRelationAttribute
		u.Type = AttributeTypeUserRelationAttribute
		return nil
	}

	var addressAttribute AddressAttribute = AddressAttribute{}
	if err := utils.UnmarshalJSON(data, &addressAttribute, "", true, nil); err == nil {
		u.AddressAttribute = &addressAttribute
		u.Type = AttributeTypeAddressAttribute
		return nil
	}

	var addressRelationAttribute AddressRelationAttribute = AddressRelationAttribute{}
	if err := utils.UnmarshalJSON(data, &addressRelationAttribute, "", true, nil); err == nil {
		u.AddressRelationAttribute = &addressRelationAttribute
		u.Type = AttributeTypeAddressRelationAttribute
		return nil
	}

	var paymentMethodRelationAttribute PaymentMethodRelationAttribute = PaymentMethodRelationAttribute{}
	if err := utils.UnmarshalJSON(data, &paymentMethodRelationAttribute, "", true, nil); err == nil {
		u.PaymentMethodRelationAttribute = &paymentMethodRelationAttribute
		u.Type = AttributeTypePaymentMethodRelationAttribute
		return nil
	}

	var tagsAttribute TagsAttribute = TagsAttribute{}
	if err := utils.UnmarshalJSON(data, &tagsAttribute, "", true, nil); err == nil {
		u.TagsAttribute = &tagsAttribute
		u.Type = AttributeTypeTagsAttribute
		return nil
	}

	var messageEmailAddressAttribute MessageEmailAddressAttribute = MessageEmailAddressAttribute{}
	if err := utils.UnmarshalJSON(data, &messageEmailAddressAttribute, "", true, nil); err == nil {
		u.MessageEmailAddressAttribute = &messageEmailAddressAttribute
		u.Type = AttributeTypeMessageEmailAddressAttribute
		return nil
	}

	var numberAttribute NumberAttribute = NumberAttribute{}
	if err := utils.UnmarshalJSON(data, &numberAttribute, "", true, nil); err == nil {
		u.NumberAttribute = &numberAttribute
		u.Type = AttributeTypeNumberAttribute
		return nil
	}

	var internalAttribute InternalAttribute = InternalAttribute{}
	if err := utils.UnmarshalJSON(data, &internalAttribute, "", true, nil); err == nil {
		u.InternalAttribute = &internalAttribute
		u.Type = AttributeTypeInternalAttribute
		return nil
	}

	var orderedListAttribute OrderedListAttribute = OrderedListAttribute{}
	if err := utils.UnmarshalJSON(data, &orderedListAttribute, "", true, nil); err == nil {
		u.OrderedListAttribute = &orderedListAttribute
		u.Type = AttributeTypeOrderedListAttribute
		return nil
	}

	var fileAttribute FileAttribute = FileAttribute{}
	if err := utils.UnmarshalJSON(data, &fileAttribute, "", true, nil); err == nil {
		u.FileAttribute = &fileAttribute
		u.Type = AttributeTypeFileAttribute
		return nil
	}

	var partnerStatusAttribute PartnerStatusAttribute = PartnerStatusAttribute{}
	if err := utils.UnmarshalJSON(data, &partnerStatusAttribute, "", true, nil); err == nil {
		u.PartnerStatusAttribute = &partnerStatusAttribute
		u.Type = AttributeTypePartnerStatusAttribute
		return nil
	}

	var invitationEmailAttribute InvitationEmailAttribute = InvitationEmailAttribute{}
	if err := utils.UnmarshalJSON(data, &invitationEmailAttribute, "", true, nil); err == nil {
		u.InvitationEmailAttribute = &invitationEmailAttribute
		u.Type = AttributeTypeInvitationEmailAttribute
		return nil
	}

	var automationAttribute AutomationAttribute = AutomationAttribute{}
	if err := utils.UnmarshalJSON(data, &automationAttribute, "", true, nil); err == nil {
		u.AutomationAttribute = &automationAttribute
		u.Type = AttributeTypeAutomationAttribute
		return nil
	}

	var internalUserAttribute InternalUserAttribute = InternalUserAttribute{}
	if err := utils.UnmarshalJSON(data, &internalUserAttribute, "", true, nil); err == nil {
		u.InternalUserAttribute = &internalUserAttribute
		u.Type = AttributeTypeInternalUserAttribute
		return nil
	}

	var purposeAttribute PurposeAttribute = PurposeAttribute{}
	if err := utils.UnmarshalJSON(data, &purposeAttribute, "", true, nil); err == nil {
		u.PurposeAttribute = &purposeAttribute
		u.Type = AttributeTypePurposeAttribute
		return nil
	}

	var partnerOrganisationAttribute PartnerOrganisationAttribute = PartnerOrganisationAttribute{}
	if err := utils.UnmarshalJSON(data, &partnerOrganisationAttribute, "", true, nil); err == nil {
		u.PartnerOrganisationAttribute = &partnerOrganisationAttribute
		u.Type = AttributeTypePartnerOrganisationAttribute
		return nil
	}

	var portalAccessAttribute PortalAccessAttribute = PortalAccessAttribute{}
	if err := utils.UnmarshalJSON(data, &portalAccessAttribute, "", true, nil); err == nil {
		u.PortalAccessAttribute = &portalAccessAttribute
		u.Type = AttributeTypePortalAccessAttribute
		return nil
	}

	var phoneAttribute PhoneAttribute = PhoneAttribute{}
	if err := utils.UnmarshalJSON(data, &phoneAttribute, "", true, nil); err == nil {
		u.PhoneAttribute = &phoneAttribute
		u.Type = AttributeTypePhoneAttribute
		return nil
	}

	var emailAttribute EmailAttribute = EmailAttribute{}
	if err := utils.UnmarshalJSON(data, &emailAttribute, "", true, nil); err == nil {
		u.EmailAttribute = &emailAttribute
		u.Type = AttributeTypeEmailAttribute
		return nil
	}

	var paymentAttribute PaymentAttribute = PaymentAttribute{}
	if err := utils.UnmarshalJSON(data, &paymentAttribute, "", true, nil); err == nil {
		u.PaymentAttribute = &paymentAttribute
		u.Type = AttributeTypePaymentAttribute
		return nil
	}

	var priceComponentAttribute PriceComponentAttribute = PriceComponentAttribute{}
	if err := utils.UnmarshalJSON(data, &priceComponentAttribute, "", true, nil); err == nil {
		u.PriceComponentAttribute = &priceComponentAttribute
		u.Type = AttributeTypePriceComponentAttribute
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Attribute", string(data))
}

func (u Attribute) MarshalJSON() ([]byte, error) {
	if u.TextAttribute != nil {
		return utils.MarshalJSON(u.TextAttribute, "", true)
	}

	if u.LinkAttribute != nil {
		return utils.MarshalJSON(u.LinkAttribute, "", true)
	}

	if u.DateAttribute != nil {
		return utils.MarshalJSON(u.DateAttribute, "", true)
	}

	if u.CountryAttribute != nil {
		return utils.MarshalJSON(u.CountryAttribute, "", true)
	}

	if u.BooleanAttribute != nil {
		return utils.MarshalJSON(u.BooleanAttribute, "", true)
	}

	if u.SelectAttribute != nil {
		return utils.MarshalJSON(u.SelectAttribute, "", true)
	}

	if u.MultiSelectAttribute != nil {
		return utils.MarshalJSON(u.MultiSelectAttribute, "", true)
	}

	if u.StatusAttribute != nil {
		return utils.MarshalJSON(u.StatusAttribute, "", true)
	}

	if u.SequenceAttribute != nil {
		return utils.MarshalJSON(u.SequenceAttribute, "", true)
	}

	if u.RelationAttribute != nil {
		return utils.MarshalJSON(u.RelationAttribute, "", true)
	}

	if u.UserRelationAttribute != nil {
		return utils.MarshalJSON(u.UserRelationAttribute, "", true)
	}

	if u.AddressAttribute != nil {
		return utils.MarshalJSON(u.AddressAttribute, "", true)
	}

	if u.AddressRelationAttribute != nil {
		return utils.MarshalJSON(u.AddressRelationAttribute, "", true)
	}

	if u.PaymentMethodRelationAttribute != nil {
		return utils.MarshalJSON(u.PaymentMethodRelationAttribute, "", true)
	}

	if u.CurrencyAttribute != nil {
		return utils.MarshalJSON(u.CurrencyAttribute, "", true)
	}

	if u.TagsAttribute != nil {
		return utils.MarshalJSON(u.TagsAttribute, "", true)
	}

	if u.MessageEmailAddressAttribute != nil {
		return utils.MarshalJSON(u.MessageEmailAddressAttribute, "", true)
	}

	if u.NumberAttribute != nil {
		return utils.MarshalJSON(u.NumberAttribute, "", true)
	}

	if u.ConsentAttribute != nil {
		return utils.MarshalJSON(u.ConsentAttribute, "", true)
	}

	if u.InternalAttribute != nil {
		return utils.MarshalJSON(u.InternalAttribute, "", true)
	}

	if u.OrderedListAttribute != nil {
		return utils.MarshalJSON(u.OrderedListAttribute, "", true)
	}

	if u.FileAttribute != nil {
		return utils.MarshalJSON(u.FileAttribute, "", true)
	}

	if u.ComputedAttribute != nil {
		return utils.MarshalJSON(u.ComputedAttribute, "", true)
	}

	if u.PartnerStatusAttribute != nil {
		return utils.MarshalJSON(u.PartnerStatusAttribute, "", true)
	}

	if u.InvitationEmailAttribute != nil {
		return utils.MarshalJSON(u.InvitationEmailAttribute, "", true)
	}

	if u.AutomationAttribute != nil {
		return utils.MarshalJSON(u.AutomationAttribute, "", true)
	}

	if u.InternalUserAttribute != nil {
		return utils.MarshalJSON(u.InternalUserAttribute, "", true)
	}

	if u.PurposeAttribute != nil {
		return utils.MarshalJSON(u.PurposeAttribute, "", true)
	}

	if u.PartnerOrganisationAttribute != nil {
		return utils.MarshalJSON(u.PartnerOrganisationAttribute, "", true)
	}

	if u.PortalAccessAttribute != nil {
		return utils.MarshalJSON(u.PortalAccessAttribute, "", true)
	}

	if u.PhoneAttribute != nil {
		return utils.MarshalJSON(u.PhoneAttribute, "", true)
	}

	if u.EmailAttribute != nil {
		return utils.MarshalJSON(u.EmailAttribute, "", true)
	}

	if u.PaymentAttribute != nil {
		return utils.MarshalJSON(u.PaymentAttribute, "", true)
	}

	if u.PriceComponentAttribute != nil {
		return utils.MarshalJSON(u.PriceComponentAttribute, "", true)
	}

	return nil, errors.New("could not marshal union type Attribute: all fields are null")
}
