// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

// ChangesetCreatorType - Type of actor that created the changeset
type ChangesetCreatorType string

const (
	ChangesetCreatorTypeUser       ChangesetCreatorType = "user"
	ChangesetCreatorTypePortalUser ChangesetCreatorType = "portal_user"
	ChangesetCreatorTypeAPIClient  ChangesetCreatorType = "api_client"
	ChangesetCreatorTypeAutomation ChangesetCreatorType = "automation"
)

func (e ChangesetCreatorType) ToPointer() *ChangesetCreatorType {
	return &e
}
func (e *ChangesetCreatorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		fallthrough
	case "portal_user":
		fallthrough
	case "api_client":
		fallthrough
	case "automation":
		*e = ChangesetCreatorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChangesetCreatorType: %v", v)
	}
}

// ChangesetCreator - Identifies the actor that created the changeset.
type ChangesetCreator struct {
	// ID of the actor (user ID, portal user ID, API client ID, etc.)
	ID *string `json:"id,omitempty"`
	// Type of actor that created the changeset
	Type *ChangesetCreatorType `json:"type,omitempty"`
}

func (c ChangesetCreator) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChangesetCreator) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChangesetCreator) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChangesetCreator) GetType() *ChangesetCreatorType {
	if c == nil {
		return nil
	}
	return c.Type
}
