// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

type EntityDefaultEditViewType string

const (
	EntityDefaultEditViewTypeDefault EntityDefaultEditViewType = "default"
)

func (e EntityDefaultEditViewType) ToPointer() *EntityDefaultEditViewType {
	return &e
}
func (e *EntityDefaultEditViewType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "default":
		*e = EntityDefaultEditViewType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityDefaultEditViewType: %v", v)
	}
}

type EntityDefaultEdit struct {
	SearchParams map[string]string `json:"search_params,omitempty"`
	// List of attribute names that we show in the summary header
	SummaryAttributes []string                   `json:"summary_attributes,omitempty"`
	ViewType          *EntityDefaultEditViewType `json:"view_type,omitempty"`
}

func (e EntityDefaultEdit) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityDefaultEdit) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityDefaultEdit) GetSearchParams() map[string]string {
	if e == nil {
		return nil
	}
	return e.SearchParams
}

func (e *EntityDefaultEdit) GetSummaryAttributes() []string {
	if e == nil {
		return nil
	}
	return e.SummaryAttributes
}

func (e *EntityDefaultEdit) GetViewType() *EntityDefaultEditViewType {
	if e == nil {
		return nil
	}
	return e.ViewType
}
