// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

// Aggs - Aggregation supported by ElasticSearch allows summarizing data as metrics, statistics, or other analytics.
type Aggs struct {
}

type SearchAfterType string

const (
	SearchAfterTypeStr    SearchAfterType = "str"
	SearchAfterTypeNumber SearchAfterType = "number"
)

type SearchAfter struct {
	Str    *string  `queryParam:"inline" name:"search_after"`
	Number *float64 `queryParam:"inline" name:"search_after"`

	Type SearchAfterType
}

func CreateSearchAfterStr(str string) SearchAfter {
	typ := SearchAfterTypeStr

	return SearchAfter{
		Str:  &str,
		Type: typ,
	}
}

func CreateSearchAfterNumber(number float64) SearchAfter {
	typ := SearchAfterTypeNumber

	return SearchAfter{
		Number: &number,
		Type:   typ,
	}
}

func (u *SearchAfter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = SearchAfterTypeStr
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = SearchAfterTypeNumber
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SearchAfter", string(data))
}

func (u SearchAfter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type SearchAfter: all fields are null")
}

type SortType string

const (
	SortTypeStr        SortType = "str"
	SortTypeArrayOfStr SortType = "arrayOfStr"
)

// Sort - You can pass one sort field or an array of sort fields. Each sort field can be a string
type Sort struct {
	Str        *string  `queryParam:"inline" name:"sort"`
	ArrayOfStr []string `queryParam:"inline" name:"sort"`

	Type SortType
}

func CreateSortStr(str string) Sort {
	typ := SortTypeStr

	return Sort{
		Str:  &str,
		Type: typ,
	}
}

func CreateSortArrayOfStr(arrayOfStr []string) Sort {
	typ := SortTypeArrayOfStr

	return Sort{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *Sort) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = SortTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = SortTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Sort", string(data))
}

func (u Sort) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type Sort: all fields are null")
}

type EntityListParams struct {
	// Aggregation supported by ElasticSearch allows summarizing data as metrics, statistics, or other analytics.
	Aggs *Aggs `json:"aggs,omitempty"`
	// Allow running the listing without any schema filter. This is disabled by default to prevent security and performance issues if done by an accident.
	AllowTargetingAllSchemas *bool `default:"false" json:"allow_targeting_all_schemas"`
	// List of entity fields to include or exclude in the response
	//
	// Use ! to exclude fields, e.g. `!_id` to exclude the `_id` field.
	//
	// Globbing and globstart (**) is supported for nested fields.
	//
	Fields []string `json:"fields,omitempty"`
	// A subset of simplified Elasticsearch query clauses. The default operator is a logical AND. Use nested $and, $or, $not to combine filters using different logical operators.
	Filter []SearchFilter `json:"filter"`
	// The offset from which to start the search results.
	// Only one of `from` or `search_after` should be used.
	//
	From      *int64 `default:"0" json:"from"`
	Highlight any    `json:"highlight,omitempty"`
	// When true, enables entity hydration to resolve nested $relation & $relation_ref references in-place.
	Hydrate *bool `default:"false" json:"hydrate"`
	// Whether to include deleted entities in the search results
	// - `true`: include deleted entities
	// - `false`: exclude deleted entities
	// - `only`: include only deleted entities
	//
	// By default, no deleted entities are included in the search results.
	//
	IncludeDeleted *EntitySearchIncludeDeletedParam `default:"false" json:"include_deleted"`
	// The sort values from which to start the search results.
	// Only one of `from` or `search_after` should be used.
	// It is strongly recommended to always use the `sort_end` field from the last search result.
	// Used for deep pagination, typically together with `stable_query_id` to maintain the context between requests.
	// Requires explicit sort to work reliably.
	// Typically used sort fields are `_id` or `_created_at`.
	//
	SearchAfter []*SearchAfter `json:"search_after,omitempty"`
	// Max search size is 1000 with higher values defaulting to 1000
	Size *int64 `default:"10" json:"size"`
	// You can pass one sort field or an array of sort fields. Each sort field can be a string
	Sort *Sort `json:"sort,omitempty"`
	// A TTL (in seconds) that specifies how long the context should be maintained.
	// Defaults to 30 seconds; configurable up to 60 seconds to prevent abuse.
	// A value of 0 can be provided the close the context after the query.
	// Defaults to none.
	//
	StableFor *int64 `json:"stable_for,omitempty"`
	// A unique identifier of the query context from the last stable query.
	// The context is maintained for the duration of the stable_for value.
	//
	StableQueryID *string `json:"stable_query_id,omitempty"`
}

func (e EntityListParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityListParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"filter"}); err != nil {
		return err
	}
	return nil
}

func (o *EntityListParams) GetAggs() *Aggs {
	if o == nil {
		return nil
	}
	return o.Aggs
}

func (o *EntityListParams) GetAllowTargetingAllSchemas() *bool {
	if o == nil {
		return nil
	}
	return o.AllowTargetingAllSchemas
}

func (o *EntityListParams) GetFields() []string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *EntityListParams) GetFilter() []SearchFilter {
	if o == nil {
		return []SearchFilter{}
	}
	return o.Filter
}

func (o *EntityListParams) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *EntityListParams) GetHighlight() any {
	if o == nil {
		return nil
	}
	return o.Highlight
}

func (o *EntityListParams) GetHydrate() *bool {
	if o == nil {
		return nil
	}
	return o.Hydrate
}

func (o *EntityListParams) GetIncludeDeleted() *EntitySearchIncludeDeletedParam {
	if o == nil {
		return nil
	}
	return o.IncludeDeleted
}

func (o *EntityListParams) GetSearchAfter() []*SearchAfter {
	if o == nil {
		return nil
	}
	return o.SearchAfter
}

func (o *EntityListParams) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *EntityListParams) GetSort() *Sort {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *EntityListParams) GetStableFor() *int64 {
	if o == nil {
		return nil
	}
	return o.StableFor
}

func (o *EntityListParams) GetStableQueryID() *string {
	if o == nil {
		return nil
	}
	return o.StableQueryID
}
