// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"time"
)

// EntityItemACL - Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
type EntityItemACL struct {
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
	Delete               []string `json:"delete,omitempty"`
	Edit                 []string `json:"edit,omitempty"`
	View                 []string `json:"view,omitempty"`
}

func (e EntityItemACL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityItemACL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityItemACL) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *EntityItemACL) GetDelete() []string {
	if e == nil {
		return nil
	}
	return e.Delete
}

func (e *EntityItemACL) GetEdit() []string {
	if e == nil {
		return nil
	}
	return e.Edit
}

func (e *EntityItemACL) GetView() []string {
	if e == nil {
		return nil
	}
	return e.View
}

type EntityItem struct {
	AdditionalProperties any            `additionalProperties:"true" json:"-"`
	ACL                  *EntityItemACL `json:"_acl,omitempty"`
	CreatedAt            *time.Time     `json:"_created_at"`
	DeletedAt            *time.Time     `json:"_deleted_at,omitempty"`
	ID                   string         `json:"_id"`
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	// Organization Id the entity belongs to
	Org     string        `json:"_org"`
	Owners  []EntityOwner `json:"_owners,omitempty"`
	Purpose []string      `json:"_purpose,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema string   `json:"_schema"`
	Tags   []string `json:"_tags,omitempty"`
	// Title of entity
	Title     *string    `json:"_title"`
	UpdatedAt *time.Time `json:"_updated_at"`
}

func (e EntityItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"_created_at", "_id", "_org", "_schema", "_title", "_updated_at"}); err != nil {
		return err
	}
	return nil
}

func (e *EntityItem) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *EntityItem) GetACL() *EntityItemACL {
	if e == nil {
		return nil
	}
	return e.ACL
}

func (e *EntityItem) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *EntityItem) GetDeletedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.DeletedAt
}

func (e *EntityItem) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EntityItem) GetManifest() []string {
	if e == nil {
		return nil
	}
	return e.Manifest
}

func (e *EntityItem) GetOrg() string {
	if e == nil {
		return ""
	}
	return e.Org
}

func (e *EntityItem) GetOwners() []EntityOwner {
	if e == nil {
		return nil
	}
	return e.Owners
}

func (e *EntityItem) GetPurpose() []string {
	if e == nil {
		return nil
	}
	return e.Purpose
}

func (e *EntityItem) GetSchema() string {
	if e == nil {
		return ""
	}
	return e.Schema
}

func (e *EntityItem) GetTags() []string {
	if e == nil {
		return nil
	}
	return e.Tags
}

func (e *EntityItem) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *EntityItem) GetUpdatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}
