// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"time"
)

// ACL - Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
type ACL struct {
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
	Delete               []string `json:"delete,omitempty"`
	Edit                 []string `json:"edit,omitempty"`
	View                 []string `json:"view,omitempty"`
}

func (a ACL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ACL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ACL) GetAdditionalProperties() any {
	if a == nil {
		return nil
	}
	return a.AdditionalProperties
}

func (a *ACL) GetDelete() []string {
	if a == nil {
		return nil
	}
	return a.Delete
}

func (a *ACL) GetEdit() []string {
	if a == nil {
		return nil
	}
	return a.Edit
}

func (a *ACL) GetView() []string {
	if a == nil {
		return nil
	}
	return a.View
}

type Entity struct {
	AdditionalProperties any        `additionalProperties:"true" json:"-"`
	ACL                  *ACL       `json:"_acl,omitempty"`
	CreatedAt            *time.Time `json:"_created_at,omitempty"`
	DeletedAt            *time.Time `json:"_deleted_at,omitempty"`
	ID                   *string    `json:"_id,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	// Organization Id the entity belongs to
	Org     *string       `json:"_org,omitempty"`
	Owners  []EntityOwner `json:"_owners,omitempty"`
	Purpose []string      `json:"_purpose,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema *string  `json:"_schema,omitempty"`
	Tags   []string `json:"_tags,omitempty"`
	// Title of entity
	Title     *string    `json:"_title,omitempty"`
	UpdatedAt *time.Time `json:"_updated_at,omitempty"`
}

func (e Entity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Entity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Entity) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *Entity) GetACL() *ACL {
	if e == nil {
		return nil
	}
	return e.ACL
}

func (e *Entity) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *Entity) GetDeletedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.DeletedAt
}

func (e *Entity) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Entity) GetManifest() []string {
	if e == nil {
		return nil
	}
	return e.Manifest
}

func (e *Entity) GetOrg() *string {
	if e == nil {
		return nil
	}
	return e.Org
}

func (e *Entity) GetOwners() []EntityOwner {
	if e == nil {
		return nil
	}
	return e.Owners
}

func (e *Entity) GetPurpose() []string {
	if e == nil {
		return nil
	}
	return e.Purpose
}

func (e *Entity) GetSchema() *string {
	if e == nil {
		return nil
	}
	return e.Schema
}

func (e *Entity) GetTags() []string {
	if e == nil {
		return nil
	}
	return e.Tags
}

func (e *Entity) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *Entity) GetUpdatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}

type EntityInput struct {
	AdditionalProperties any     `additionalProperties:"true" json:"-"`
	ACL                  *ACL    `json:"_acl,omitempty"`
	ID                   *string `json:"_id,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	Purpose  []string `json:"_purpose,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema *string  `json:"_schema,omitempty"`
	Tags   []string `json:"_tags,omitempty"`
	// Title of entity
	Title *string `json:"_title,omitempty"`
}

func (e EntityInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityInput) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *EntityInput) GetACL() *ACL {
	if e == nil {
		return nil
	}
	return e.ACL
}

func (e *EntityInput) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EntityInput) GetManifest() []string {
	if e == nil {
		return nil
	}
	return e.Manifest
}

func (e *EntityInput) GetPurpose() []string {
	if e == nil {
		return nil
	}
	return e.Purpose
}

func (e *EntityInput) GetSchema() *string {
	if e == nil {
		return nil
	}
	return e.Schema
}

func (e *EntityInput) GetTags() []string {
	if e == nil {
		return nil
	}
	return e.Tags
}

func (e *EntityInput) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}
