// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EntityValidationErrorParams - Additional parameters for the error
type EntityValidationErrorParams struct {
	// The type of the error
	Type *string `json:"type,omitempty"`
}

func (e *EntityValidationErrorParams) GetType() *string {
	if e == nil {
		return nil
	}
	return e.Type
}

// EntityValidationError - Validation error for an entity attribute
type EntityValidationError struct {
	// Error code identifier
	Code string `json:"code"`
	// A human-readable message describing the error
	Message string `json:"message"`
	// Additional parameters for the error
	Params EntityValidationErrorParams `json:"params"`
	// The path to the attribute that failed validation
	Path []string `json:"path"`
}

func (e *EntityValidationError) GetCode() string {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *EntityValidationError) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *EntityValidationError) GetParams() EntityValidationErrorParams {
	if e == nil {
		return EntityValidationErrorParams{}
	}
	return e.Params
}

func (e *EntityValidationError) GetPath() []string {
	if e == nil {
		return []string{}
	}
	return e.Path
}
