// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

// EntityOwner - The user / organization owning this entity.
//
// Note: Owner implicitly has access to the entity regardless of ACLs.
type EntityOwner struct {
	OrgID  string  `json:"org_id"`
	UserID *string `json:"user_id,omitempty"`
}

func (e EntityOwner) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityOwner) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"org_id"}); err != nil {
		return err
	}
	return nil
}

func (e *EntityOwner) GetOrgID() string {
	if e == nil {
		return ""
	}
	return e.OrgID
}

func (e *EntityOwner) GetUserID() *string {
	if e == nil {
		return nil
	}
	return e.UserID
}
