// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

type EntitySchemaGroupWithCompositeIDInfoTooltipTitle struct {
	// Default string for info tooltip
	Default *string `json:"default,omitempty"`
	// Translation key for info tooltip
	Key *string `json:"key,omitempty"`
}

func (e *EntitySchemaGroupWithCompositeIDInfoTooltipTitle) GetDefault() *string {
	if e == nil {
		return nil
	}
	return e.Default
}

func (e *EntitySchemaGroupWithCompositeIDInfoTooltipTitle) GetKey() *string {
	if e == nil {
		return nil
	}
	return e.Key
}

// EntitySchemaGroupWithCompositeID - a readonly computed ID for the group including schema slug and the group ID
type EntitySchemaGroupWithCompositeID struct {
	// Manifest ID used to create/update the schema group
	Manifest []string `json:"_manifest,omitempty"`
	// Only render group when one of the purposes is enabled
	Purpose     []string `json:"_purpose,omitempty"`
	CompositeID *string  `json:"composite_id,omitempty"`
	// Expanded by default
	Expanded *bool `default:"false" json:"expanded"`
	// This group should only be active when the feature flag is enabled
	FeatureFlag      *string                                           `json:"feature_flag,omitempty"`
	ID               *string                                           `json:"id,omitempty"`
	InfoTooltipTitle *EntitySchemaGroupWithCompositeIDInfoTooltipTitle `json:"info_tooltip_title,omitempty"`
	Label            string                                            `json:"label"`
	// Render order of the group
	Order *int64 `default:"0" json:"order"`
	// Only render group when render_condition resolves to true
	RenderCondition *string `json:"render_condition,omitempty"`
	// Schema slug the group belongs to
	Schema *string `json:"schema,omitempty"`
	// This group should only be active when all the settings have the correct value
	SettingsFlag []SettingFlag `json:"settings_flag,omitempty"`
}

func (e EntitySchemaGroupWithCompositeID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntitySchemaGroupWithCompositeID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"label"}); err != nil {
		return err
	}
	return nil
}

func (e *EntitySchemaGroupWithCompositeID) GetManifest() []string {
	if e == nil {
		return nil
	}
	return e.Manifest
}

func (e *EntitySchemaGroupWithCompositeID) GetPurpose() []string {
	if e == nil {
		return nil
	}
	return e.Purpose
}

func (e *EntitySchemaGroupWithCompositeID) GetCompositeID() *string {
	if e == nil {
		return nil
	}
	return e.CompositeID
}

func (e *EntitySchemaGroupWithCompositeID) GetExpanded() *bool {
	if e == nil {
		return nil
	}
	return e.Expanded
}

func (e *EntitySchemaGroupWithCompositeID) GetFeatureFlag() *string {
	if e == nil {
		return nil
	}
	return e.FeatureFlag
}

func (e *EntitySchemaGroupWithCompositeID) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EntitySchemaGroupWithCompositeID) GetInfoTooltipTitle() *EntitySchemaGroupWithCompositeIDInfoTooltipTitle {
	if e == nil {
		return nil
	}
	return e.InfoTooltipTitle
}

func (e *EntitySchemaGroupWithCompositeID) GetLabel() string {
	if e == nil {
		return ""
	}
	return e.Label
}

func (e *EntitySchemaGroupWithCompositeID) GetOrder() *int64 {
	if e == nil {
		return nil
	}
	return e.Order
}

func (e *EntitySchemaGroupWithCompositeID) GetRenderCondition() *string {
	if e == nil {
		return nil
	}
	return e.RenderCondition
}

func (e *EntitySchemaGroupWithCompositeID) GetSchema() *string {
	if e == nil {
		return nil
	}
	return e.Schema
}

func (e *EntitySchemaGroupWithCompositeID) GetSettingsFlag() []SettingFlag {
	if e == nil {
		return nil
	}
	return e.SettingsFlag
}

// EntitySchemaGroupWithCompositeIDInput - a readonly computed ID for the group including schema slug and the group ID
type EntitySchemaGroupWithCompositeIDInput struct {
	// Manifest ID used to create/update the schema group
	Manifest []string `json:"_manifest,omitempty"`
	// Only render group when one of the purposes is enabled
	Purpose []string `json:"_purpose,omitempty"`
	// Expanded by default
	Expanded *bool `default:"false" json:"expanded"`
	// This group should only be active when the feature flag is enabled
	FeatureFlag      *string                                           `json:"feature_flag,omitempty"`
	ID               *string                                           `json:"id,omitempty"`
	InfoTooltipTitle *EntitySchemaGroupWithCompositeIDInfoTooltipTitle `json:"info_tooltip_title,omitempty"`
	Label            string                                            `json:"label"`
	// Render order of the group
	Order *int64 `default:"0" json:"order"`
	// Only render group when render_condition resolves to true
	RenderCondition *string `json:"render_condition,omitempty"`
	// Schema slug the group belongs to
	Schema *string `json:"schema,omitempty"`
	// This group should only be active when all the settings have the correct value
	SettingsFlag []SettingFlag `json:"settings_flag,omitempty"`
}

func (e EntitySchemaGroupWithCompositeIDInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntitySchemaGroupWithCompositeIDInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"label"}); err != nil {
		return err
	}
	return nil
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetManifest() []string {
	if e == nil {
		return nil
	}
	return e.Manifest
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetPurpose() []string {
	if e == nil {
		return nil
	}
	return e.Purpose
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetExpanded() *bool {
	if e == nil {
		return nil
	}
	return e.Expanded
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetFeatureFlag() *string {
	if e == nil {
		return nil
	}
	return e.FeatureFlag
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetInfoTooltipTitle() *EntitySchemaGroupWithCompositeIDInfoTooltipTitle {
	if e == nil {
		return nil
	}
	return e.InfoTooltipTitle
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetLabel() string {
	if e == nil {
		return ""
	}
	return e.Label
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetOrder() *int64 {
	if e == nil {
		return nil
	}
	return e.Order
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetRenderCondition() *string {
	if e == nil {
		return nil
	}
	return e.RenderCondition
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetSchema() *string {
	if e == nil {
		return nil
	}
	return e.Schema
}

func (e *EntitySchemaGroupWithCompositeIDInput) GetSettingsFlag() []SettingFlag {
	if e == nil {
		return nil
	}
	return e.SettingsFlag
}
