// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Schema - The value of the failing keyword in the schema.
type Schema struct {
}

type EntityValidationV2Error struct {
	// The data validated by the keyword.
	Data map[string]any `json:"data,omitempty"`
	// JSON Pointer to the location in the data instance (e.g., `"/prop/1/subProp"`).
	InstancePath string `json:"instance_path"`
	// validation keyword.
	Keyword string `json:"keyword"`
	// The error message.
	Message *string `json:"message,omitempty"`
	// Additional information about error.
	Params map[string]any `json:"params"`
	// The schema containing the keyword.
	ParentSchema map[string]any `json:"parent_schema,omitempty"`
	// Set for errors in `propertyNames` keyword schema. `instance_path` still points to the object in this case.
	PropertyName *string `json:"property_name,omitempty"`
	// The value of the failing keyword in the schema.
	Schema *Schema `json:"schema,omitempty"`
	// JSON Pointer to the location of the failing keyword in the schema.
	SchemaPath string `json:"schema_path"`
}

func (e *EntityValidationV2Error) GetData() map[string]any {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EntityValidationV2Error) GetInstancePath() string {
	if e == nil {
		return ""
	}
	return e.InstancePath
}

func (e *EntityValidationV2Error) GetKeyword() string {
	if e == nil {
		return ""
	}
	return e.Keyword
}

func (e *EntityValidationV2Error) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *EntityValidationV2Error) GetParams() map[string]any {
	if e == nil {
		return map[string]any{}
	}
	return e.Params
}

func (e *EntityValidationV2Error) GetParentSchema() map[string]any {
	if e == nil {
		return nil
	}
	return e.ParentSchema
}

func (e *EntityValidationV2Error) GetPropertyName() *string {
	if e == nil {
		return nil
	}
	return e.PropertyName
}

func (e *EntityValidationV2Error) GetSchema() *Schema {
	if e == nil {
		return nil
	}
	return e.Schema
}

func (e *EntityValidationV2Error) GetSchemaPath() string {
	if e == nil {
		return ""
	}
	return e.SchemaPath
}
