// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

type KeyType string

const (
	KeyTypeStr        KeyType = "str"
	KeyTypeArrayOfStr KeyType = "arrayOfStr"
)

// Key - For type=entry_match: business key(s) within each entry used to match proposed entries against incoming entries.
type Key struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type KeyType
}

func CreateKeyStr(str string) Key {
	typ := KeyTypeStr

	return Key{
		Str:  &str,
		Type: typ,
	}
}

func CreateKeyArrayOfStr(arrayOfStr []string) Key {
	typ := KeyTypeArrayOfStr

	return Key{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *Key) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  KeyTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  KeyTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Key", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Key", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(KeyType)
	switch best.Type {
	case KeyTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case KeyTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Key", string(data))
}

func (u Key) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type Key: all fields are null")
}

// Mode - For type=entry_match and type=set_equivalent: how strict the comparison is.
// - `subset` (default for entry_match): every proposed entry must exist in incoming; extra incoming entries are allowed.
// - `exact_set` (default for set_equivalent): the two sides must contain the same entries (order-insensitive, multiset semantics).
type Mode string

const (
	ModeSubset   Mode = "subset"
	ModeExactSet Mode = "exact_set"
)

func (e Mode) ToPointer() *Mode {
	return &e
}
func (e *Mode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "subset":
		fallthrough
	case "exact_set":
		*e = Mode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Mode: %v", v)
	}
}

// FuzzyConfigType - Which fuzzy algorithm to apply.
type FuzzyConfigType string

const (
	FuzzyConfigTypeSuffix         FuzzyConfigType = "suffix"
	FuzzyConfigTypeDigitsOnly     FuzzyConfigType = "digits_only"
	FuzzyConfigTypeNormalizePhone FuzzyConfigType = "normalize_phone"
	FuzzyConfigTypeIgnoreFields   FuzzyConfigType = "ignore_fields"
	FuzzyConfigTypeSetEquivalent  FuzzyConfigType = "set_equivalent"
	FuzzyConfigTypeEntryMatch     FuzzyConfigType = "entry_match"
	FuzzyConfigTypeRelationSet    FuzzyConfigType = "relation_set"
	FuzzyConfigTypeRegex          FuzzyConfigType = "regex"
)

func (e FuzzyConfigType) ToPointer() *FuzzyConfigType {
	return &e
}
func (e *FuzzyConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "suffix":
		fallthrough
	case "digits_only":
		fallthrough
	case "normalize_phone":
		fallthrough
	case "ignore_fields":
		fallthrough
	case "set_equivalent":
		fallthrough
	case "entry_match":
		fallthrough
	case "relation_set":
		fallthrough
	case "regex":
		*e = FuzzyConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FuzzyConfigType: %v", v)
	}
}

// FuzzyConfig - Configuration for fuzzy auto-clear matching on `edit_mode: external` attributes.
// Not used for `edit_mode: approval`.
//
// Type compatibility with attribute shape is enforced at schema save time:
// - scalar string attributes: `suffix`, `digits_only`, `regex`
// - repeatable attributes: `set_equivalent`, `entry_match`, `ignore_fields`, `normalize_phone`
// - relation attributes: `relation_set`
type FuzzyConfig struct {
	// For type=normalize_phone: country dialing code digits to strip (e.g. '49' for Germany). No '+' prefix.
	CountryCode *string `json:"country_code,omitempty"`
	// For type=ignore_fields and type=set_equivalent: field names to exclude when comparing array entries. `_id` is always stripped by the platform regardless of this config.
	FieldsToIgnore []string `json:"fields_to_ignore,omitempty"`
	// For type=entry_match: business key(s) within each entry used to match proposed entries against incoming entries.
	Key *Key `json:"key,omitempty"`
	// For type=normalize_phone: attribute key within array entries to compare on (e.g. 'phone_number').
	MatchOn *string `json:"match_on,omitempty"`
	// For type=entry_match and type=set_equivalent: how strict the comparison is.
	// - `subset` (default for entry_match): every proposed entry must exist in incoming; extra incoming entries are allowed.
	// - `exact_set` (default for set_equivalent): the two sides must contain the same entries (order-insensitive, multiset semantics).
	//
	Mode *Mode `json:"mode,omitempty"`
	// For type=relation_set: when true, relation order is significant. Defaults to false (order-insensitive).
	Ordered *bool `json:"ordered,omitempty"`
	// For type=regex: regular expression pattern to test the incoming value against.
	Pattern *string `json:"pattern,omitempty"`
	// For type=regex: flags to apply to the regex (e.g. 'i' for case-insensitive).
	RegexFlags *string `json:"regex_flags,omitempty"`
	// For type=relation_set: when true, each relation item's `_tags` must match on both sides (order-insensitive). Defaults to false — `_tags` are stripped before compare.
	RequireTagsMatch *bool `json:"require_tags_match,omitempty"`
	// For type=suffix: number of characters to compare from end of string.
	SuffixLength *int64 `json:"suffix_length,omitempty"`
	// Which fuzzy algorithm to apply.
	Type FuzzyConfigType `json:"type"`
}

func (f FuzzyConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FuzzyConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FuzzyConfig) GetCountryCode() *string {
	if f == nil {
		return nil
	}
	return f.CountryCode
}

func (f *FuzzyConfig) GetFieldsToIgnore() []string {
	if f == nil {
		return nil
	}
	return f.FieldsToIgnore
}

func (f *FuzzyConfig) GetKey() *Key {
	if f == nil {
		return nil
	}
	return f.Key
}

func (f *FuzzyConfig) GetMatchOn() *string {
	if f == nil {
		return nil
	}
	return f.MatchOn
}

func (f *FuzzyConfig) GetMode() *Mode {
	if f == nil {
		return nil
	}
	return f.Mode
}

func (f *FuzzyConfig) GetOrdered() *bool {
	if f == nil {
		return nil
	}
	return f.Ordered
}

func (f *FuzzyConfig) GetPattern() *string {
	if f == nil {
		return nil
	}
	return f.Pattern
}

func (f *FuzzyConfig) GetRegexFlags() *string {
	if f == nil {
		return nil
	}
	return f.RegexFlags
}

func (f *FuzzyConfig) GetRequireTagsMatch() *bool {
	if f == nil {
		return nil
	}
	return f.RequireTagsMatch
}

func (f *FuzzyConfig) GetSuffixLength() *int64 {
	if f == nil {
		return nil
	}
	return f.SuffixLength
}

func (f *FuzzyConfig) GetType() FuzzyConfigType {
	if f == nil {
		return FuzzyConfigType("")
	}
	return f.Type
}
