// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

type GetRelationsRespType string

const (
	GetRelationsRespTypeRelationItem   GetRelationsRespType = "RelationItem"
	GetRelationsRespTypeRelationEntity GetRelationsRespType = "RelationEntity"
)

type GetRelationsResp struct {
	RelationItem   *RelationItem   `queryParam:"inline,name=GetRelationsResp"`
	RelationEntity *RelationEntity `queryParam:"inline,name=GetRelationsResp"`

	Type GetRelationsRespType
}

func CreateGetRelationsRespRelationItem(relationItem RelationItem) GetRelationsResp {
	typ := GetRelationsRespTypeRelationItem

	return GetRelationsResp{
		RelationItem: &relationItem,
		Type:         typ,
	}
}

func CreateGetRelationsRespRelationEntity(relationEntity RelationEntity) GetRelationsResp {
	typ := GetRelationsRespTypeRelationEntity

	return GetRelationsResp{
		RelationEntity: &relationEntity,
		Type:           typ,
	}
}

func (u *GetRelationsResp) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var relationEntity RelationEntity = RelationEntity{}
	if err := utils.UnmarshalJSON(data, &relationEntity, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetRelationsRespTypeRelationEntity,
			Value: &relationEntity,
		})
	}

	var relationItem RelationItem = RelationItem{}
	if err := utils.UnmarshalJSON(data, &relationItem, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetRelationsRespTypeRelationItem,
			Value: &relationItem,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetRelationsResp", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetRelationsResp", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(GetRelationsRespType)
	switch best.Type {
	case GetRelationsRespTypeRelationEntity:
		u.RelationEntity = best.Value.(*RelationEntity)
		return nil
	case GetRelationsRespTypeRelationItem:
		u.RelationItem = best.Value.(*RelationItem)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetRelationsResp", string(data))
}

func (u GetRelationsResp) MarshalJSON() ([]byte, error) {
	if u.RelationItem != nil {
		return utils.MarshalJSON(u.RelationItem, "", true)
	}

	if u.RelationEntity != nil {
		return utils.MarshalJSON(u.RelationEntity, "", true)
	}

	return nil, errors.New("could not marshal union type GetRelationsResp: all fields are null")
}
