// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetRelatedEntitiesCount struct {
	Hits *int64 `json:"hits,omitempty"`
}

func (g *GetRelatedEntitiesCount) GetHits() *int64 {
	if g == nil {
		return nil
	}
	return g.Hits
}
