// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetRelatedEntitiesCount struct {
	Hits *int64 `json:"hits,omitempty"`
}

func (o *GetRelatedEntitiesCount) GetHits() *int64 {
	if o == nil {
		return nil
	}
	return o.Hits
}
