// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GraphDefinition struct {
	// List of edge definitions connecting nodes
	Edges []GraphEdge `json:"edges"`
	// List of node definitions in the graph
	Nodes []GraphNode `json:"nodes"`
}

func (o *GraphDefinition) GetEdges() []GraphEdge {
	if o == nil {
		return []GraphEdge{}
	}
	return o.Edges
}

func (o *GraphDefinition) GetNodes() []GraphNode {
	if o == nil {
		return []GraphNode{}
	}
	return o.Nodes
}
