// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

type Divider string

const (
	DividerTopDivider    Divider = "top_divider"
	DividerBottomDivider Divider = "bottom_divider"
)

func (e Divider) ToPointer() *Divider {
	return &e
}
func (e *Divider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "top_divider":
		fallthrough
	case "bottom_divider":
		*e = Divider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Divider: %v", v)
	}
}

type GroupHeadlineType string

const (
	GroupHeadlineTypeHeadline GroupHeadlineType = "headline"
)

func (e GroupHeadlineType) ToPointer() *GroupHeadlineType {
	return &e
}
func (e *GroupHeadlineType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "headline":
		*e = GroupHeadlineType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GroupHeadlineType: %v", v)
	}
}

type GroupHeadline struct {
	// Manifest ID used to create/update the schema group headline
	Manifest      []string `json:"_manifest,omitempty"`
	Purpose       []string `json:"_purpose,omitempty"`
	Divider       *Divider `json:"divider,omitempty"`
	EnableDivider *bool    `default:"false" json:"enable_divider"`
	// The group of headline attribute
	Group  string  `json:"group"`
	ID     *string `json:"id,omitempty"`
	Label  string  `json:"label"`
	Layout *string `json:"layout,omitempty"`
	Name   string  `json:"name"`
	// The order of headline attribute
	Order *int64            `json:"order,omitempty"`
	Type  GroupHeadlineType `json:"type"`
}

func (g GroupHeadline) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GroupHeadline) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"group", "label", "name", "type"}); err != nil {
		return err
	}
	return nil
}

func (g *GroupHeadline) GetManifest() []string {
	if g == nil {
		return nil
	}
	return g.Manifest
}

func (g *GroupHeadline) GetPurpose() []string {
	if g == nil {
		return nil
	}
	return g.Purpose
}

func (g *GroupHeadline) GetDivider() *Divider {
	if g == nil {
		return nil
	}
	return g.Divider
}

func (g *GroupHeadline) GetEnableDivider() *bool {
	if g == nil {
		return nil
	}
	return g.EnableDivider
}

func (g *GroupHeadline) GetGroup() string {
	if g == nil {
		return ""
	}
	return g.Group
}

func (g *GroupHeadline) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GroupHeadline) GetLabel() string {
	if g == nil {
		return ""
	}
	return g.Label
}

func (g *GroupHeadline) GetLayout() *string {
	if g == nil {
		return nil
	}
	return g.Layout
}

func (g *GroupHeadline) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GroupHeadline) GetOrder() *int64 {
	if g == nil {
		return nil
	}
	return g.Order
}

func (g *GroupHeadline) GetType() GroupHeadlineType {
	if g == nil {
		return GroupHeadlineType("")
	}
	return g.Type
}
