// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

// InternalUserAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type InternalUserAttributeConstraints struct {
}

func (i InternalUserAttributeConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InternalUserAttributeConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

// InternalUserAttributeInfoHelpers - A set of configurations meant to document and assist the user in filling the attribute.
type InternalUserAttributeInfoHelpers struct {
	// The name of the custom component to be used as the hint helper.
	// The component should be registered in the `@epilot360/entity-ui` on the index of the components directory.
	// When specified it overrides the `hint_text` or `hint_text_key` configuration.
	//
	HintCustomComponent *string `json:"hint_custom_component,omitempty"`
	// The text to be displayed in the attribute hint helper.
	// When specified it overrides the `hint_text_key` configuration.
	//
	HintText *string `json:"hint_text,omitempty"`
	// The key of the hint text to be displayed in the attribute hint helper.
	// The key should be a valid i18n key.
	//
	HintTextKey *string `json:"hint_text_key,omitempty"`
	// The placement of the hint tooltip.
	// The value should be a valid `@mui/core` tooltip placement.
	//
	HintTooltipPlacement *string `json:"hint_tooltip_placement,omitempty"`
}

func (i InternalUserAttributeInfoHelpers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InternalUserAttributeInfoHelpers) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InternalUserAttributeInfoHelpers) GetHintCustomComponent() *string {
	if i == nil {
		return nil
	}
	return i.HintCustomComponent
}

func (i *InternalUserAttributeInfoHelpers) GetHintText() *string {
	if i == nil {
		return nil
	}
	return i.HintText
}

func (i *InternalUserAttributeInfoHelpers) GetHintTextKey() *string {
	if i == nil {
		return nil
	}
	return i.HintTextKey
}

func (i *InternalUserAttributeInfoHelpers) GetHintTooltipPlacement() *string {
	if i == nil {
		return nil
	}
	return i.HintTooltipPlacement
}

type InternalUserAttributeType string

const (
	InternalUserAttributeTypeInternalUser InternalUserAttributeType = "internal_user"
)

func (e InternalUserAttributeType) ToPointer() *InternalUserAttributeType {
	return &e
}
func (e *InternalUserAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "internal_user":
		*e = InternalUserAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternalUserAttributeType: %v", v)
	}
}

// InternalUserAttribute - Epilot internal user info
type InternalUserAttribute struct {
	// Manifest ID used to create/update the schema attribute
	Manifest []string `json:"_manifest,omitempty"`
	Purpose  []string `json:"_purpose,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints  *InternalUserAttributeConstraints `json:"constraints,omitempty"`
	DefaultValue any                               `json:"default_value,omitempty"`
	Deprecated   *bool                             `default:"false" json:"deprecated"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group      *string `json:"group,omitempty"`
	HasPrimary *bool   `json:"has_primary,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon *string `json:"icon,omitempty"`
	// ID for the entity attribute
	ID *string `json:"id,omitempty"`
	// A set of configurations meant to document and assist the user in filling the attribute.
	InfoHelpers *InternalUserAttributeInfoHelpers `json:"info_helpers,omitempty"`
	Label       string                            `json:"label"`
	Layout      *string                           `json:"layout,omitempty"`
	Name        string                            `json:"name"`
	// Attribute sort order (ascending) in group
	Order                 *int64  `json:"order,omitempty"`
	Placeholder           *string `json:"placeholder,omitempty"`
	PreviewValueFormatter *string `json:"preview_value_formatter,omitempty"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `json:"protected,omitempty"`
	Readonly  *bool `default:"false" json:"readonly"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string `json:"render_condition,omitempty"`
	// The attribute is a repeatable
	Repeatable *bool `json:"repeatable,omitempty"`
	Required   *bool `default:"false" json:"required"`
	// This attribute should only be active when one of the provided settings have the correct value
	SettingsFlag []SettingFlag `json:"settings_flag,omitempty"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable *bool `json:"show_in_table,omitempty"`
	// Allow sorting by this attribute in table views if `show_in_table` is true
	Sortable       *bool                     `default:"true" json:"sortable"`
	Type           InternalUserAttributeType `json:"type"`
	ValueFormatter *string                   `json:"value_formatter,omitempty"`
}

func (i InternalUserAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InternalUserAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"label", "name", "type"}); err != nil {
		return err
	}
	return nil
}

func (i *InternalUserAttribute) GetManifest() []string {
	if i == nil {
		return nil
	}
	return i.Manifest
}

func (i *InternalUserAttribute) GetPurpose() []string {
	if i == nil {
		return nil
	}
	return i.Purpose
}

func (i *InternalUserAttribute) GetConstraints() *InternalUserAttributeConstraints {
	if i == nil {
		return nil
	}
	return i.Constraints
}

func (i *InternalUserAttribute) GetDefaultValue() any {
	if i == nil {
		return nil
	}
	return i.DefaultValue
}

func (i *InternalUserAttribute) GetDeprecated() *bool {
	if i == nil {
		return nil
	}
	return i.Deprecated
}

func (i *InternalUserAttribute) GetEntityBuilderDisableEdit() *bool {
	if i == nil {
		return nil
	}
	return i.EntityBuilderDisableEdit
}

func (i *InternalUserAttribute) GetFeatureFlag() *string {
	if i == nil {
		return nil
	}
	return i.FeatureFlag
}

func (i *InternalUserAttribute) GetGroup() *string {
	if i == nil {
		return nil
	}
	return i.Group
}

func (i *InternalUserAttribute) GetHasPrimary() *bool {
	if i == nil {
		return nil
	}
	return i.HasPrimary
}

func (i *InternalUserAttribute) GetHidden() *bool {
	if i == nil {
		return nil
	}
	return i.Hidden
}

func (i *InternalUserAttribute) GetHideLabel() *bool {
	if i == nil {
		return nil
	}
	return i.HideLabel
}

func (i *InternalUserAttribute) GetIcon() *string {
	if i == nil {
		return nil
	}
	return i.Icon
}

func (i *InternalUserAttribute) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InternalUserAttribute) GetInfoHelpers() *InternalUserAttributeInfoHelpers {
	if i == nil {
		return nil
	}
	return i.InfoHelpers
}

func (i *InternalUserAttribute) GetLabel() string {
	if i == nil {
		return ""
	}
	return i.Label
}

func (i *InternalUserAttribute) GetLayout() *string {
	if i == nil {
		return nil
	}
	return i.Layout
}

func (i *InternalUserAttribute) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *InternalUserAttribute) GetOrder() *int64 {
	if i == nil {
		return nil
	}
	return i.Order
}

func (i *InternalUserAttribute) GetPlaceholder() *string {
	if i == nil {
		return nil
	}
	return i.Placeholder
}

func (i *InternalUserAttribute) GetPreviewValueFormatter() *string {
	if i == nil {
		return nil
	}
	return i.PreviewValueFormatter
}

func (i *InternalUserAttribute) GetProtected() *bool {
	if i == nil {
		return nil
	}
	return i.Protected
}

func (i *InternalUserAttribute) GetReadonly() *bool {
	if i == nil {
		return nil
	}
	return i.Readonly
}

func (i *InternalUserAttribute) GetRenderCondition() *string {
	if i == nil {
		return nil
	}
	return i.RenderCondition
}

func (i *InternalUserAttribute) GetRepeatable() *bool {
	if i == nil {
		return nil
	}
	return i.Repeatable
}

func (i *InternalUserAttribute) GetRequired() *bool {
	if i == nil {
		return nil
	}
	return i.Required
}

func (i *InternalUserAttribute) GetSettingsFlag() []SettingFlag {
	if i == nil {
		return nil
	}
	return i.SettingsFlag
}

func (i *InternalUserAttribute) GetShowInTable() *bool {
	if i == nil {
		return nil
	}
	return i.ShowInTable
}

func (i *InternalUserAttribute) GetSortable() *bool {
	if i == nil {
		return nil
	}
	return i.Sortable
}

func (i *InternalUserAttribute) GetType() InternalUserAttributeType {
	if i == nil {
		return InternalUserAttributeType("")
	}
	return i.Type
}

func (i *InternalUserAttribute) GetValueFormatter() *string {
	if i == nil {
		return nil
	}
	return i.ValueFormatter
}
