// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type ListSavedViewsResults struct {
	Hits    *float64        `json:"hits,omitempty"`
	Results []SavedViewItem `json:"results,omitempty"`
}

func (o *ListSavedViewsResults) GetHits() *float64 {
	if o == nil {
		return nil
	}
	return o.Hits
}

func (o *ListSavedViewsResults) GetResults() []SavedViewItem {
	if o == nil {
		return nil
	}
	return o.Results
}
