// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// MatchStrategy - Strategy for auto-clearing a changeset on an `edit_mode: external` attribute
// when a direct write (`?direct=true`) arrives — typically an ERP inbound sync.
// Ignored for `edit_mode: approval`, which does not auto-clear and is resolved
// exclusively via the `:apply` / `:dismiss` changeset endpoints.
// - `exact`: The inbound value must exactly match the proposed value (deep equality).
// - `fuzzy`: The inbound value is compared using the configured `fuzzy_config` algorithm.
// - `any`: Any update to the attribute clears the changeset, regardless of value.
type MatchStrategy string

const (
	MatchStrategyExact MatchStrategy = "exact"
	MatchStrategyFuzzy MatchStrategy = "fuzzy"
	MatchStrategyAny   MatchStrategy = "any"
)

func (e MatchStrategy) ToPointer() *MatchStrategy {
	return &e
}
func (e *MatchStrategy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "exact":
		fallthrough
	case "fuzzy":
		fallthrough
	case "any":
		*e = MatchStrategy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MatchStrategy: %v", v)
	}
}
