// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"time"
)

// NullableEntityACL - Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
type NullableEntityACL struct {
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
	Delete               []string `json:"delete,omitempty"`
	Edit                 []string `json:"edit,omitempty"`
	View                 []string `json:"view,omitempty"`
}

func (n NullableEntityACL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableEntityACL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableEntityACL) GetAdditionalProperties() any {
	if n == nil {
		return nil
	}
	return n.AdditionalProperties
}

func (n *NullableEntityACL) GetDelete() []string {
	if n == nil {
		return nil
	}
	return n.Delete
}

func (n *NullableEntityACL) GetEdit() []string {
	if n == nil {
		return nil
	}
	return n.Edit
}

func (n *NullableEntityACL) GetView() []string {
	if n == nil {
		return nil
	}
	return n.View
}

type NullableEntity struct {
	AdditionalProperties any                `additionalProperties:"true" json:"-"`
	ACL                  *NullableEntityACL `json:"_acl,omitempty"`
	CreatedAt            *time.Time         `json:"_created_at,omitempty"`
	DeletedAt            *time.Time         `json:"_deleted_at,omitempty"`
	ID                   *string            `json:"_id,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	// Organization Id the entity belongs to
	Org     *string       `json:"_org,omitempty"`
	Owners  []EntityOwner `json:"_owners,omitempty"`
	Purpose []string      `json:"_purpose,omitempty"`
	// Automatically computed purpose names from _purpose attribute
	PurposeName []string `json:"_purpose_name,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema *string  `json:"_schema,omitempty"`
	Tags   []string `json:"_tags,omitempty"`
	// Title of entity
	Title     *string    `json:"_title,omitempty"`
	UpdatedAt *time.Time `json:"_updated_at,omitempty"`
}

func (n NullableEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableEntity) GetAdditionalProperties() any {
	if n == nil {
		return nil
	}
	return n.AdditionalProperties
}

func (n *NullableEntity) GetACL() *NullableEntityACL {
	if n == nil {
		return nil
	}
	return n.ACL
}

func (n *NullableEntity) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NullableEntity) GetDeletedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.DeletedAt
}

func (n *NullableEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableEntity) GetManifest() []string {
	if n == nil {
		return nil
	}
	return n.Manifest
}

func (n *NullableEntity) GetOrg() *string {
	if n == nil {
		return nil
	}
	return n.Org
}

func (n *NullableEntity) GetOwners() []EntityOwner {
	if n == nil {
		return nil
	}
	return n.Owners
}

func (n *NullableEntity) GetPurpose() []string {
	if n == nil {
		return nil
	}
	return n.Purpose
}

func (n *NullableEntity) GetPurposeName() []string {
	if n == nil {
		return nil
	}
	return n.PurposeName
}

func (n *NullableEntity) GetSchema() *string {
	if n == nil {
		return nil
	}
	return n.Schema
}

func (n *NullableEntity) GetTags() []string {
	if n == nil {
		return nil
	}
	return n.Tags
}

func (n *NullableEntity) GetTitle() *string {
	if n == nil {
		return nil
	}
	return n.Title
}

func (n *NullableEntity) GetUpdatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.UpdatedAt
}
