// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

type SavedViewPartialSource string

const (
	SavedViewPartialSourceSystem    SavedViewPartialSource = "SYSTEM"
	SavedViewPartialSourceBlueprint SavedViewPartialSource = "BLUEPRINT"
)

func (e SavedViewPartialSource) ToPointer() *SavedViewPartialSource {
	return &e
}
func (e *SavedViewPartialSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SYSTEM":
		fallthrough
	case "BLUEPRINT":
		*e = SavedViewPartialSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SavedViewPartialSource: %v", v)
	}
}

// SavedViewPartial2 - A system-created view
type SavedViewPartial2 struct {
	AdditionalProperties any                     `additionalProperties:"true" json:"-"`
	Source               *SavedViewPartialSource `json:"source,omitempty"`
}

func (s SavedViewPartial2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedViewPartial2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedViewPartial2) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}

func (s *SavedViewPartial2) GetSource() *SavedViewPartialSource {
	if s == nil {
		return nil
	}
	return s.Source
}

// #region class-body-savedviewpartial2
// #endregion class-body-savedviewpartial2

// SavedViewPartial1 - A user that created the view
type SavedViewPartial1 struct {
	UserID *string `json:"user_id,omitempty"`
}

func (s SavedViewPartial1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedViewPartial1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedViewPartial1) GetUserID() *string {
	if s == nil {
		return nil
	}
	return s.UserID
}

// #region class-body-savedviewpartial1
// #endregion class-body-savedviewpartial1

type SavedViewPartialCreatedByType string

const (
	SavedViewPartialCreatedByTypeSavedViewPartial1 SavedViewPartialCreatedByType = "SavedViewPartial_1"
	SavedViewPartialCreatedByTypeSavedViewPartial2 SavedViewPartialCreatedByType = "SavedViewPartial_2"
)

type SavedViewPartialCreatedBy struct {
	SavedViewPartial1 *SavedViewPartial1 `queryParam:"inline" union:"member"`
	SavedViewPartial2 *SavedViewPartial2 `queryParam:"inline" union:"member"`

	Type SavedViewPartialCreatedByType
}

func CreateSavedViewPartialCreatedBySavedViewPartial1(savedViewPartial1 SavedViewPartial1) SavedViewPartialCreatedBy {
	typ := SavedViewPartialCreatedByTypeSavedViewPartial1

	return SavedViewPartialCreatedBy{
		SavedViewPartial1: &savedViewPartial1,
		Type:              typ,
	}
}

func CreateSavedViewPartialCreatedBySavedViewPartial2(savedViewPartial2 SavedViewPartial2) SavedViewPartialCreatedBy {
	typ := SavedViewPartialCreatedByTypeSavedViewPartial2

	return SavedViewPartialCreatedBy{
		SavedViewPartial2: &savedViewPartial2,
		Type:              typ,
	}
}

func (u *SavedViewPartialCreatedBy) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var savedViewPartial1 SavedViewPartial1 = SavedViewPartial1{}
	if err := utils.UnmarshalJSON(data, &savedViewPartial1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SavedViewPartialCreatedByTypeSavedViewPartial1,
			Value: &savedViewPartial1,
		})
	}

	var savedViewPartial2 SavedViewPartial2 = SavedViewPartial2{}
	if err := utils.UnmarshalJSON(data, &savedViewPartial2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SavedViewPartialCreatedByTypeSavedViewPartial2,
			Value: &savedViewPartial2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SavedViewPartialCreatedBy", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SavedViewPartialCreatedBy", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SavedViewPartialCreatedByType)
	switch best.Type {
	case SavedViewPartialCreatedByTypeSavedViewPartial1:
		u.SavedViewPartial1 = best.Value.(*SavedViewPartial1)
		return nil
	case SavedViewPartialCreatedByTypeSavedViewPartial2:
		u.SavedViewPartial2 = best.Value.(*SavedViewPartial2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SavedViewPartialCreatedBy", string(data))
}

func (u SavedViewPartialCreatedBy) MarshalJSON() ([]byte, error) {
	if u.SavedViewPartial1 != nil {
		return utils.MarshalJSON(u.SavedViewPartial1, "", true)
	}

	if u.SavedViewPartial2 != nil {
		return utils.MarshalJSON(u.SavedViewPartial2, "", true)
	}

	return nil, errors.New("could not marshal union type SavedViewPartialCreatedBy: all fields are null")
}

// SavedViewPartial - A saved entity view
type SavedViewPartial struct {
	CreatedBy *SavedViewPartialCreatedBy `json:"created_by,omitempty"`
	// List of users (IDs) that have favorited the view
	IsFavoritedBy []string `json:"isFavoritedBy,omitempty"`
	// User-friendly identifier for the saved view
	Name *string `json:"name,omitempty"`
	// Organisation ID a view belongs to
	Org *string `json:"org,omitempty"`
	// boolean property for if a view is shared with organisation
	Shared *bool `json:"shared,omitempty"`
	// List of users ('${userId}'), user groups ('group_${groupId}'), or partner users ('${partnerOrgId}_${partnerUserId}') that the view is shared with
	SharedWith []string `json:"shared_with,omitempty"`
	// list of schemas a view can belong to
	Slug     []string       `json:"slug,omitempty"`
	UIConfig map[string]any `json:"ui_config,omitempty"`
}

func (s *SavedViewPartial) GetCreatedBy() *SavedViewPartialCreatedBy {
	if s == nil {
		return nil
	}
	return s.CreatedBy
}

func (s *SavedViewPartial) GetIsFavoritedBy() []string {
	if s == nil {
		return nil
	}
	return s.IsFavoritedBy
}

func (s *SavedViewPartial) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SavedViewPartial) GetOrg() *string {
	if s == nil {
		return nil
	}
	return s.Org
}

func (s *SavedViewPartial) GetShared() *bool {
	if s == nil {
		return nil
	}
	return s.Shared
}

func (s *SavedViewPartial) GetSharedWith() []string {
	if s == nil {
		return nil
	}
	return s.SharedWith
}

func (s *SavedViewPartial) GetSlug() []string {
	if s == nil {
		return nil
	}
	return s.Slug
}

func (s *SavedViewPartial) GetUIConfig() map[string]any {
	if s == nil {
		return nil
	}
	return s.UIConfig
}
