// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

// ColumnHeader - Configuration for column headers in transposed mode
type ColumnHeader struct {
	// Starting index value for the template placeholder
	Start *int64 `default:"0" json:"start"`
	// Header label pattern with {{i}} as index placeholder (e.g., "Year {{i}}")
	Template *string `json:"template,omitempty"`
}

func (c ColumnHeader) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ColumnHeader) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ColumnHeader) GetStart() *int64 {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *ColumnHeader) GetTemplate() *string {
	if c == nil {
		return nil
	}
	return c.Template
}

// TableAttributeSchemasType - The data type for cells in this column
type TableAttributeSchemasType string

const (
	TableAttributeSchemasTypeString  TableAttributeSchemasType = "string"
	TableAttributeSchemasTypeNumber  TableAttributeSchemasType = "number"
	TableAttributeSchemasTypeDate    TableAttributeSchemasType = "date"
	TableAttributeSchemasTypeBoolean TableAttributeSchemasType = "boolean"
)

func (e TableAttributeSchemasType) ToPointer() *TableAttributeSchemasType {
	return &e
}
func (e *TableAttributeSchemasType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "string":
		fallthrough
	case "number":
		fallthrough
	case "date":
		fallthrough
	case "boolean":
		*e = TableAttributeSchemasType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TableAttributeSchemasType: %v", v)
	}
}

type Columns struct {
	// When true, the row is rendered in bold (only applies in transposed mode)
	Bold *bool `default:"false" json:"bold"`
	// Display label for the column header
	Label string `json:"label"`
	// The column identifier (used as object key in row data)
	Name string `json:"name"`
	// Whether this column is required for each row
	Required *bool `default:"false" json:"required"`
	// The data type for cells in this column
	Type *TableAttributeSchemasType `default:"string" json:"type"`
	// Optional column width (e.g., "100px", "20%")
	Width *string `json:"width,omitempty"`
}

func (c Columns) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Columns) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Columns) GetBold() *bool {
	if c == nil {
		return nil
	}
	return c.Bold
}

func (c *Columns) GetLabel() string {
	if c == nil {
		return ""
	}
	return c.Label
}

func (c *Columns) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Columns) GetRequired() *bool {
	if c == nil {
		return nil
	}
	return c.Required
}

func (c *Columns) GetType() *TableAttributeSchemasType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *Columns) GetWidth() *string {
	if c == nil {
		return nil
	}
	return c.Width
}

// TableAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type TableAttributeConstraints struct {
}

func (t TableAttributeConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TableAttributeConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

// TableAttributeInfoHelpers - A set of configurations meant to document and assist the user in filling the attribute.
type TableAttributeInfoHelpers struct {
	// The name of the custom component to be used as the hint helper.
	// The component should be registered in the `@epilot360/entity-ui` on the index of the components directory.
	// When specified it overrides the `hint_text` or `hint_text_key` configuration.
	//
	HintCustomComponent *string `json:"hint_custom_component,omitempty"`
	// The text to be displayed in the attribute hint helper.
	// When specified it overrides the `hint_text_key` configuration.
	//
	HintText *string `json:"hint_text,omitempty"`
	// The key of the hint text to be displayed in the attribute hint helper.
	// The key should be a valid i18n key.
	//
	HintTextKey *string `json:"hint_text_key,omitempty"`
	// The placement of the hint tooltip.
	// The value should be a valid `@mui/core` tooltip placement.
	//
	HintTooltipPlacement *string `json:"hint_tooltip_placement,omitempty"`
}

func (t TableAttributeInfoHelpers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TableAttributeInfoHelpers) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TableAttributeInfoHelpers) GetHintCustomComponent() *string {
	if t == nil {
		return nil
	}
	return t.HintCustomComponent
}

func (t *TableAttributeInfoHelpers) GetHintText() *string {
	if t == nil {
		return nil
	}
	return t.HintText
}

func (t *TableAttributeInfoHelpers) GetHintTextKey() *string {
	if t == nil {
		return nil
	}
	return t.HintTextKey
}

func (t *TableAttributeInfoHelpers) GetHintTooltipPlacement() *string {
	if t == nil {
		return nil
	}
	return t.HintTooltipPlacement
}

type TableAttributeType string

const (
	TableAttributeTypeTable TableAttributeType = "table"
)

func (e TableAttributeType) ToPointer() *TableAttributeType {
	return &e
}
func (e *TableAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "table":
		*e = TableAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TableAttributeType: %v", v)
	}
}

// TableAttribute - Dynamic data table with configurable columns. Data is stored as an array of objects where each object represents a row.
type TableAttribute struct {
	// Manifest ID used to create/update the schema attribute
	Manifest []string `json:"_manifest,omitempty"`
	Purpose  []string `json:"_purpose,omitempty"`
	// Configuration for column headers in transposed mode
	ColumnHeader *ColumnHeader `json:"column_header,omitempty"`
	// Column definitions for the table
	Columns []Columns `json:"columns,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints  *TableAttributeConstraints `json:"constraints,omitempty"`
	DefaultValue any                        `json:"default_value,omitempty"`
	Deprecated   *bool                      `default:"false" json:"deprecated"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// When set to true, this attribute will be excluded from search fields.
	// Use this for fields that should not be matched during entity search operations,
	// such as internal hashes or identifiers that might accidentally match search terms.
	//
	ExcludeFromSearch *bool `default:"false" json:"exclude_from_search"`
	// When set to true, this attribute will always be searchable regardless of
	// the ELASTIC_MAX_SEARCH_FIELDS limit. Use this for critical search fields
	// that must always be included in search operations.
	//
	ExplicitSearchable *bool `default:"false" json:"explicit_searchable"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group      *string `json:"group,omitempty"`
	HasPrimary *bool   `json:"has_primary,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon *string `json:"icon,omitempty"`
	// ID for the entity attribute
	ID *string `json:"id,omitempty"`
	// A set of configurations meant to document and assist the user in filling the attribute.
	InfoHelpers *TableAttributeInfoHelpers `json:"info_helpers,omitempty"`
	Label       string                     `json:"label"`
	Layout      *string                    `json:"layout,omitempty"`
	// Maximum number of rows allowed (or maximum periods when transposed)
	MaxRows *int64 `json:"max_rows,omitempty"`
	// Minimum number of rows required
	MinRows *int64 `default:"0" json:"min_rows"`
	Name    string `json:"name"`
	// Attribute sort order (ascending) in group
	Order                 *int64  `json:"order,omitempty"`
	Placeholder           *string `json:"placeholder,omitempty"`
	PreviewValueFormatter *string `json:"preview_value_formatter,omitempty"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `json:"protected,omitempty"`
	Readonly  *bool `default:"false" json:"readonly"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string `json:"render_condition,omitempty"`
	// The attribute is a repeatable
	Repeatable *bool `json:"repeatable,omitempty"`
	Required   *bool `default:"false" json:"required"`
	// This attribute should only be active when one of the provided settings have the correct value
	SettingsFlag []SettingFlag `json:"settings_flag,omitempty"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable *bool `json:"show_in_table,omitempty"`
	// Allow sorting by this attribute in table views if `show_in_table` is true
	Sortable *bool `default:"true" json:"sortable"`
	// Enable transposed layout where rows become metrics and columns become periods
	Transposed     *bool              `default:"false" json:"transposed"`
	Type           TableAttributeType `json:"type"`
	ValueFormatter *string            `json:"value_formatter,omitempty"`
}

func (t TableAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TableAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TableAttribute) GetManifest() []string {
	if t == nil {
		return nil
	}
	return t.Manifest
}

func (t *TableAttribute) GetPurpose() []string {
	if t == nil {
		return nil
	}
	return t.Purpose
}

func (t *TableAttribute) GetColumnHeader() *ColumnHeader {
	if t == nil {
		return nil
	}
	return t.ColumnHeader
}

func (t *TableAttribute) GetColumns() []Columns {
	if t == nil {
		return nil
	}
	return t.Columns
}

func (t *TableAttribute) GetConstraints() *TableAttributeConstraints {
	if t == nil {
		return nil
	}
	return t.Constraints
}

func (t *TableAttribute) GetDefaultValue() any {
	if t == nil {
		return nil
	}
	return t.DefaultValue
}

func (t *TableAttribute) GetDeprecated() *bool {
	if t == nil {
		return nil
	}
	return t.Deprecated
}

func (t *TableAttribute) GetEntityBuilderDisableEdit() *bool {
	if t == nil {
		return nil
	}
	return t.EntityBuilderDisableEdit
}

func (t *TableAttribute) GetExcludeFromSearch() *bool {
	if t == nil {
		return nil
	}
	return t.ExcludeFromSearch
}

func (t *TableAttribute) GetExplicitSearchable() *bool {
	if t == nil {
		return nil
	}
	return t.ExplicitSearchable
}

func (t *TableAttribute) GetFeatureFlag() *string {
	if t == nil {
		return nil
	}
	return t.FeatureFlag
}

func (t *TableAttribute) GetGroup() *string {
	if t == nil {
		return nil
	}
	return t.Group
}

func (t *TableAttribute) GetHasPrimary() *bool {
	if t == nil {
		return nil
	}
	return t.HasPrimary
}

func (t *TableAttribute) GetHidden() *bool {
	if t == nil {
		return nil
	}
	return t.Hidden
}

func (t *TableAttribute) GetHideLabel() *bool {
	if t == nil {
		return nil
	}
	return t.HideLabel
}

func (t *TableAttribute) GetIcon() *string {
	if t == nil {
		return nil
	}
	return t.Icon
}

func (t *TableAttribute) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TableAttribute) GetInfoHelpers() *TableAttributeInfoHelpers {
	if t == nil {
		return nil
	}
	return t.InfoHelpers
}

func (t *TableAttribute) GetLabel() string {
	if t == nil {
		return ""
	}
	return t.Label
}

func (t *TableAttribute) GetLayout() *string {
	if t == nil {
		return nil
	}
	return t.Layout
}

func (t *TableAttribute) GetMaxRows() *int64 {
	if t == nil {
		return nil
	}
	return t.MaxRows
}

func (t *TableAttribute) GetMinRows() *int64 {
	if t == nil {
		return nil
	}
	return t.MinRows
}

func (t *TableAttribute) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TableAttribute) GetOrder() *int64 {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *TableAttribute) GetPlaceholder() *string {
	if t == nil {
		return nil
	}
	return t.Placeholder
}

func (t *TableAttribute) GetPreviewValueFormatter() *string {
	if t == nil {
		return nil
	}
	return t.PreviewValueFormatter
}

func (t *TableAttribute) GetProtected() *bool {
	if t == nil {
		return nil
	}
	return t.Protected
}

func (t *TableAttribute) GetReadonly() *bool {
	if t == nil {
		return nil
	}
	return t.Readonly
}

func (t *TableAttribute) GetRenderCondition() *string {
	if t == nil {
		return nil
	}
	return t.RenderCondition
}

func (t *TableAttribute) GetRepeatable() *bool {
	if t == nil {
		return nil
	}
	return t.Repeatable
}

func (t *TableAttribute) GetRequired() *bool {
	if t == nil {
		return nil
	}
	return t.Required
}

func (t *TableAttribute) GetSettingsFlag() []SettingFlag {
	if t == nil {
		return nil
	}
	return t.SettingsFlag
}

func (t *TableAttribute) GetShowInTable() *bool {
	if t == nil {
		return nil
	}
	return t.ShowInTable
}

func (t *TableAttribute) GetSortable() *bool {
	if t == nil {
		return nil
	}
	return t.Sortable
}

func (t *TableAttribute) GetTransposed() *bool {
	if t == nil {
		return nil
	}
	return t.Transposed
}

func (t *TableAttribute) GetType() TableAttributeType {
	if t == nil {
		return TableAttributeType("")
	}
	return t.Type
}

func (t *TableAttribute) GetValueFormatter() *string {
	if t == nil {
		return nil
	}
	return t.ValueFormatter
}
