// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
	"time"
)

// Kind of taxonomy e.g. system or user_defined. By default, it's empty, which means 'user_defined'
type Kind string

const (
	KindSystem      Kind = "system"
	KindUserDefined Kind = "user_defined"
)

func (e Kind) ToPointer() *Kind {
	return &e
}
func (e *Kind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		fallthrough
	case "user_defined":
		*e = Kind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Kind: %v", v)
	}
}

// TaxonomyType - Type of taxonomy. Whether it classifies:
// - entity (default)
// - relation (for relations)
// - system (for system taxonomies - default for all slugs starting with _system_)
// - file_collection (for file collections)
type TaxonomyType string

const (
	TaxonomyTypeEntity         TaxonomyType = "entity"
	TaxonomyTypeRelation       TaxonomyType = "relation"
	TaxonomyTypeSystem         TaxonomyType = "system"
	TaxonomyTypeFileCollection TaxonomyType = "file_collection"
)

func (e TaxonomyType) ToPointer() *TaxonomyType {
	return &e
}
func (e *TaxonomyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "entity":
		fallthrough
	case "relation":
		fallthrough
	case "system":
		fallthrough
	case "file_collection":
		*e = TaxonomyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TaxonomyType: %v", v)
	}
}

type Taxonomy struct {
	// HEX Color code for the taxonomy
	Color     *string    `json:"color,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// User ID of the creator
	CreatedBy *string `json:"created_by,omitempty"`
	// Date when the taxonomy was soft-deleted (enabled: false)
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Whether the taxonomy is enabled or not
	Enabled *bool `json:"enabled,omitempty"`
	// List of locations where the taxonomy is enabled to be used. If empty, it's enabled for all locations.
	EnabledLocations []string `json:"enabled_locations,omitempty"`
	// Icon name for the taxonomy (from epilot360/icons icon set)
	Icon *string `json:"icon,omitempty"`
	// Kind of taxonomy e.g. system or user_defined. By default, it's empty, which means 'user_defined'
	Kind *Kind `json:"kind,omitempty"`
	// A human friendly name of a Taxonomy e.g. Purpose, Product Category, Folder, Tag
	Name *string `json:"name,omitempty"`
	// Position of the taxonomy
	Order *float64 `json:"order,omitempty"`
	// Plural name of a Taxonomy e.g. Purposes, Product Categories, Folders, Tags. Defaults to name is not provided.
	Plural *string `json:"plural,omitempty"`
	// URL-friendly name for taxonomy
	Slug *string `json:"slug,omitempty"`
	// Type of taxonomy. Whether it classifies:
	// - entity (default)
	// - relation (for relations)
	// - system (for system taxonomies - default for all slugs starting with _system_)
	// - file_collection (for file collections)
	//
	Type      *TaxonomyType `default:"entity" json:"type"`
	UpdatedAt *time.Time    `json:"updated_at,omitempty"`
}

func (t Taxonomy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Taxonomy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Taxonomy) GetColor() *string {
	if t == nil {
		return nil
	}
	return t.Color
}

func (t *Taxonomy) GetCreatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *Taxonomy) GetCreatedBy() *string {
	if t == nil {
		return nil
	}
	return t.CreatedBy
}

func (t *Taxonomy) GetDeletedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.DeletedAt
}

func (t *Taxonomy) GetEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.Enabled
}

func (t *Taxonomy) GetEnabledLocations() []string {
	if t == nil {
		return nil
	}
	return t.EnabledLocations
}

func (t *Taxonomy) GetIcon() *string {
	if t == nil {
		return nil
	}
	return t.Icon
}

func (t *Taxonomy) GetKind() *Kind {
	if t == nil {
		return nil
	}
	return t.Kind
}

func (t *Taxonomy) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *Taxonomy) GetOrder() *float64 {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *Taxonomy) GetPlural() *string {
	if t == nil {
		return nil
	}
	return t.Plural
}

func (t *Taxonomy) GetSlug() *string {
	if t == nil {
		return nil
	}
	return t.Slug
}

func (t *Taxonomy) GetType() *TaxonomyType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *Taxonomy) GetUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}

type TaxonomyInput struct {
	// HEX Color code for the taxonomy
	Color *string `json:"color,omitempty"`
	// Whether the taxonomy is enabled or not
	Enabled *bool `json:"enabled,omitempty"`
	// List of locations where the taxonomy is enabled to be used. If empty, it's enabled for all locations.
	EnabledLocations []string `json:"enabled_locations,omitempty"`
	// Icon name for the taxonomy (from epilot360/icons icon set)
	Icon *string `json:"icon,omitempty"`
	// A human friendly name of a Taxonomy e.g. Purpose, Product Category, Folder, Tag
	Name *string `json:"name,omitempty"`
	// Position of the taxonomy
	Order *float64 `json:"order,omitempty"`
	// Plural name of a Taxonomy e.g. Purposes, Product Categories, Folders, Tags. Defaults to name is not provided.
	Plural *string `json:"plural,omitempty"`
	// URL-friendly name for taxonomy
	Slug *string `json:"slug,omitempty"`
	// Type of taxonomy. Whether it classifies:
	// - entity (default)
	// - relation (for relations)
	// - system (for system taxonomies - default for all slugs starting with _system_)
	// - file_collection (for file collections)
	//
	Type *TaxonomyType `default:"entity" json:"type"`
}

func (t TaxonomyInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaxonomyInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaxonomyInput) GetColor() *string {
	if t == nil {
		return nil
	}
	return t.Color
}

func (t *TaxonomyInput) GetEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.Enabled
}

func (t *TaxonomyInput) GetEnabledLocations() []string {
	if t == nil {
		return nil
	}
	return t.EnabledLocations
}

func (t *TaxonomyInput) GetIcon() *string {
	if t == nil {
		return nil
	}
	return t.Icon
}

func (t *TaxonomyInput) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TaxonomyInput) GetOrder() *float64 {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *TaxonomyInput) GetPlural() *string {
	if t == nil {
		return nil
	}
	return t.Plural
}

func (t *TaxonomyInput) GetSlug() *string {
	if t == nil {
		return nil
	}
	return t.Slug
}

func (t *TaxonomyInput) GetType() *TaxonomyType {
	if t == nil {
		return nil
	}
	return t.Type
}
