// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TaxonomyBulkJobActionType string

const (
	TaxonomyBulkJobActionTypeMoveClassifications   TaxonomyBulkJobActionType = "MOVE_CLASSIFICATIONS"
	TaxonomyBulkJobActionTypeMergeClassifications  TaxonomyBulkJobActionType = "MERGE_CLASSIFICATIONS"
	TaxonomyBulkJobActionTypeDeleteClassifications TaxonomyBulkJobActionType = "DELETE_CLASSIFICATIONS"
)

func (e TaxonomyBulkJobActionType) ToPointer() *TaxonomyBulkJobActionType {
	return &e
}
func (e *TaxonomyBulkJobActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MOVE_CLASSIFICATIONS":
		fallthrough
	case "MERGE_CLASSIFICATIONS":
		fallthrough
	case "DELETE_CLASSIFICATIONS":
		*e = TaxonomyBulkJobActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TaxonomyBulkJobActionType: %v", v)
	}
}
