// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

// TextAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type TextAttributeConstraints struct {
}

func (t TextAttributeConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TextAttributeConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

// TextAttributeInfoHelpers - A set of configurations meant to document and assist the user in filling the attribute.
type TextAttributeInfoHelpers struct {
	// The name of the custom component to be used as the hint helper.
	// The component should be registered in the `@epilot360/entity-ui` on the index of the components directory.
	// When specified it overrides the `hint_text` or `hint_text_key` configuration.
	//
	HintCustomComponent *string `json:"hint_custom_component,omitempty"`
	// The text to be displayed in the attribute hint helper.
	// When specified it overrides the `hint_text_key` configuration.
	//
	HintText *string `json:"hint_text,omitempty"`
	// The key of the hint text to be displayed in the attribute hint helper.
	// The key should be a valid i18n key.
	//
	HintTextKey *string `json:"hint_text_key,omitempty"`
	// The placement of the hint tooltip.
	// The value should be a valid `@mui/core` tooltip placement.
	//
	HintTooltipPlacement *string `json:"hint_tooltip_placement,omitempty"`
}

func (t TextAttributeInfoHelpers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TextAttributeInfoHelpers) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TextAttributeInfoHelpers) GetHintCustomComponent() *string {
	if t == nil {
		return nil
	}
	return t.HintCustomComponent
}

func (t *TextAttributeInfoHelpers) GetHintText() *string {
	if t == nil {
		return nil
	}
	return t.HintText
}

func (t *TextAttributeInfoHelpers) GetHintTextKey() *string {
	if t == nil {
		return nil
	}
	return t.HintTextKey
}

func (t *TextAttributeInfoHelpers) GetHintTooltipPlacement() *string {
	if t == nil {
		return nil
	}
	return t.HintTooltipPlacement
}

type RowsType string

const (
	RowsTypeInteger RowsType = "integer"
	RowsTypeStr     RowsType = "str"
)

// Rows - Number of rows for rich_text textarea
type Rows struct {
	Integer *int64  `queryParam:"inline" name:"rows"`
	Str     *string `queryParam:"inline" name:"rows"`

	Type RowsType
}

func CreateRowsInteger(integer int64) Rows {
	typ := RowsTypeInteger

	return Rows{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateRowsStr(str string) Rows {
	typ := RowsTypeStr

	return Rows{
		Str:  &str,
		Type: typ,
	}
}

func (u *Rows) UnmarshalJSON(data []byte) error {

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = RowsTypeInteger
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = RowsTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Rows", string(data))
}

func (u Rows) MarshalJSON() ([]byte, error) {
	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type Rows: all fields are null")
}

type TextAttributeType string

const (
	TextAttributeTypeString TextAttributeType = "string"
)

func (e TextAttributeType) ToPointer() *TextAttributeType {
	return &e
}
func (e *TextAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "string":
		*e = TextAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TextAttributeType: %v", v)
	}
}

// TextAttribute - Textarea or text input
type TextAttribute struct {
	// Manifest ID used to create/update the schema attribute
	Manifest []string `json:"_manifest,omitempty"`
	Purpose  []string `json:"_purpose,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints  *TextAttributeConstraints `json:"constraints,omitempty"`
	DefaultValue any                       `json:"default_value,omitempty"`
	Deprecated   *bool                     `default:"false" json:"deprecated"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group      *string `json:"group,omitempty"`
	HasPrimary *bool   `json:"has_primary,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon *string `json:"icon,omitempty"`
	// ID for the entity attribute
	ID *string `json:"id,omitempty"`
	// A set of configurations meant to document and assist the user in filling the attribute.
	InfoHelpers *TextAttributeInfoHelpers `json:"info_helpers,omitempty"`
	Label       string                    `json:"label"`
	Layout      *string                   `json:"layout,omitempty"`
	Multiline   *bool                     `json:"multiline,omitempty"`
	Name        string                    `json:"name"`
	// Attribute sort order (ascending) in group
	Order                 *int64  `json:"order,omitempty"`
	Placeholder           *string `json:"placeholder,omitempty"`
	PreviewValueFormatter *string `json:"preview_value_formatter,omitempty"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `json:"protected,omitempty"`
	Readonly  *bool `default:"false" json:"readonly"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string `json:"render_condition,omitempty"`
	// The attribute is a repeatable
	Repeatable *bool `json:"repeatable,omitempty"`
	Required   *bool `default:"false" json:"required"`
	RichText   *bool `json:"rich_text,omitempty"`
	// Number of rows for rich_text textarea
	Rows *Rows `json:"rows,omitempty"`
	// This attribute should only be active when one of the provided settings have the correct value
	SettingsFlag []SettingFlag `json:"settings_flag,omitempty"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable *bool `json:"show_in_table,omitempty"`
	// Allow sorting by this attribute in table views if `show_in_table` is true
	Sortable       *bool             `default:"true" json:"sortable"`
	Type           TextAttributeType `json:"type"`
	ValueFormatter *string           `json:"value_formatter,omitempty"`
}

func (t TextAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TextAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"label", "name", "type"}); err != nil {
		return err
	}
	return nil
}

func (t *TextAttribute) GetManifest() []string {
	if t == nil {
		return nil
	}
	return t.Manifest
}

func (t *TextAttribute) GetPurpose() []string {
	if t == nil {
		return nil
	}
	return t.Purpose
}

func (t *TextAttribute) GetConstraints() *TextAttributeConstraints {
	if t == nil {
		return nil
	}
	return t.Constraints
}

func (t *TextAttribute) GetDefaultValue() any {
	if t == nil {
		return nil
	}
	return t.DefaultValue
}

func (t *TextAttribute) GetDeprecated() *bool {
	if t == nil {
		return nil
	}
	return t.Deprecated
}

func (t *TextAttribute) GetEntityBuilderDisableEdit() *bool {
	if t == nil {
		return nil
	}
	return t.EntityBuilderDisableEdit
}

func (t *TextAttribute) GetFeatureFlag() *string {
	if t == nil {
		return nil
	}
	return t.FeatureFlag
}

func (t *TextAttribute) GetGroup() *string {
	if t == nil {
		return nil
	}
	return t.Group
}

func (t *TextAttribute) GetHasPrimary() *bool {
	if t == nil {
		return nil
	}
	return t.HasPrimary
}

func (t *TextAttribute) GetHidden() *bool {
	if t == nil {
		return nil
	}
	return t.Hidden
}

func (t *TextAttribute) GetHideLabel() *bool {
	if t == nil {
		return nil
	}
	return t.HideLabel
}

func (t *TextAttribute) GetIcon() *string {
	if t == nil {
		return nil
	}
	return t.Icon
}

func (t *TextAttribute) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TextAttribute) GetInfoHelpers() *TextAttributeInfoHelpers {
	if t == nil {
		return nil
	}
	return t.InfoHelpers
}

func (t *TextAttribute) GetLabel() string {
	if t == nil {
		return ""
	}
	return t.Label
}

func (t *TextAttribute) GetLayout() *string {
	if t == nil {
		return nil
	}
	return t.Layout
}

func (t *TextAttribute) GetMultiline() *bool {
	if t == nil {
		return nil
	}
	return t.Multiline
}

func (t *TextAttribute) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TextAttribute) GetOrder() *int64 {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *TextAttribute) GetPlaceholder() *string {
	if t == nil {
		return nil
	}
	return t.Placeholder
}

func (t *TextAttribute) GetPreviewValueFormatter() *string {
	if t == nil {
		return nil
	}
	return t.PreviewValueFormatter
}

func (t *TextAttribute) GetProtected() *bool {
	if t == nil {
		return nil
	}
	return t.Protected
}

func (t *TextAttribute) GetReadonly() *bool {
	if t == nil {
		return nil
	}
	return t.Readonly
}

func (t *TextAttribute) GetRenderCondition() *string {
	if t == nil {
		return nil
	}
	return t.RenderCondition
}

func (t *TextAttribute) GetRepeatable() *bool {
	if t == nil {
		return nil
	}
	return t.Repeatable
}

func (t *TextAttribute) GetRequired() *bool {
	if t == nil {
		return nil
	}
	return t.Required
}

func (t *TextAttribute) GetRichText() *bool {
	if t == nil {
		return nil
	}
	return t.RichText
}

func (t *TextAttribute) GetRows() *Rows {
	if t == nil {
		return nil
	}
	return t.Rows
}

func (t *TextAttribute) GetSettingsFlag() []SettingFlag {
	if t == nil {
		return nil
	}
	return t.SettingsFlag
}

func (t *TextAttribute) GetShowInTable() *bool {
	if t == nil {
		return nil
	}
	return t.ShowInTable
}

func (t *TextAttribute) GetSortable() *bool {
	if t == nil {
		return nil
	}
	return t.Sortable
}

func (t *TextAttribute) GetType() TextAttributeType {
	if t == nil {
		return TextAttributeType("")
	}
	return t.Type
}

func (t *TextAttribute) GetValueFormatter() *string {
	if t == nil {
		return nil
	}
	return t.ValueFormatter
}
