// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/internal/utils"
)

// UserRelationAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type UserRelationAttributeConstraints struct {
}

func (u UserRelationAttributeConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserRelationAttributeConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

// UserRelationAttributeDataClassification - Data classification of the attribute, used by anonymized responses (`?anonymize=true` or tokens minted with `anonymize: true`).
//
// - `pii`: the attribute value is always anonymized in anonymized responses (use to opt in free-text fields containing personal data)
// - `public`: the attribute value is never anonymized (use to opt out fields matched by built-in defaults, e.g. non-personal identifiers)
//
// When unset, built-in defaults apply based on the attribute type (email, phone, address, payment) and a curated list of well-known PII fields.
type UserRelationAttributeDataClassification string

const (
	UserRelationAttributeDataClassificationPublic UserRelationAttributeDataClassification = "public"
	UserRelationAttributeDataClassificationPii    UserRelationAttributeDataClassification = "pii"
)

func (e UserRelationAttributeDataClassification) ToPointer() *UserRelationAttributeDataClassification {
	return &e
}
func (e *UserRelationAttributeDataClassification) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "public":
		fallthrough
	case "pii":
		*e = UserRelationAttributeDataClassification(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserRelationAttributeDataClassification: %v", v)
	}
}

// UserRelationAttributeInfoHelpers - A set of configurations meant to document and assist the user in filling the attribute.
type UserRelationAttributeInfoHelpers struct {
	// The name of the custom component to be used as the hint helper.
	// The component should be registered in the `@epilot360/entity-ui` on the index of the components directory.
	// When specified it overrides the `hint_text` or `hint_text_key` configuration.
	//
	HintCustomComponent *string `json:"hint_custom_component,omitempty"`
	// The text to be displayed in the attribute hint helper.
	// When specified it overrides the `hint_text_key` configuration.
	//
	HintText *string `json:"hint_text,omitempty"`
	// The key of the hint text to be displayed in the attribute hint helper.
	// The key should be a valid i18n key.
	//
	HintTextKey *string `json:"hint_text_key,omitempty"`
	// The placement of the hint tooltip.
	// The value should be a valid `@mui/core` tooltip placement.
	//
	HintTooltipPlacement *string `json:"hint_tooltip_placement,omitempty"`
}

func (u UserRelationAttributeInfoHelpers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserRelationAttributeInfoHelpers) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserRelationAttributeInfoHelpers) GetHintCustomComponent() *string {
	if u == nil {
		return nil
	}
	return u.HintCustomComponent
}

func (u *UserRelationAttributeInfoHelpers) GetHintText() *string {
	if u == nil {
		return nil
	}
	return u.HintText
}

func (u *UserRelationAttributeInfoHelpers) GetHintTextKey() *string {
	if u == nil {
		return nil
	}
	return u.HintTextKey
}

func (u *UserRelationAttributeInfoHelpers) GetHintTooltipPlacement() *string {
	if u == nil {
		return nil
	}
	return u.HintTooltipPlacement
}

type UserRelationAttributeType string

const (
	UserRelationAttributeTypeRelationUser UserRelationAttributeType = "relation_user"
)

func (e UserRelationAttributeType) ToPointer() *UserRelationAttributeType {
	return &e
}
func (e *UserRelationAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "relation_user":
		*e = UserRelationAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserRelationAttributeType: %v", v)
	}
}

// UserRelationAttribute - User Relationship
type UserRelationAttribute struct {
	// Manifest ID used to create/update the schema attribute
	Manifest []string `json:"_manifest,omitempty"`
	Purpose  []string `json:"_purpose,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints *UserRelationAttributeConstraints `json:"constraints,omitempty"`
	// Data classification of the attribute, used by anonymized responses (`?anonymize=true` or tokens minted with `anonymize: true`).
	//
	// - `pii`: the attribute value is always anonymized in anonymized responses (use to opt in free-text fields containing personal data)
	// - `public`: the attribute value is never anonymized (use to opt out fields matched by built-in defaults, e.g. non-personal identifiers)
	//
	// When unset, built-in defaults apply based on the attribute type (email, phone, address, payment) and a curated list of well-known PII fields.
	//
	DataClassification *UserRelationAttributeDataClassification `json:"data_classification,omitempty"`
	DefaultValue       any                                      `json:"default_value,omitempty"`
	Deprecated         *bool                                    `default:"false" json:"deprecated"`
	// Controls how updates to this attribute are handled. See the `EditMode`
	// schema for the per-mode semantics. Defaults to `direct`.
	//
	EditMode *EditMode `default:"direct" json:"edit_mode"`
	// Configuration for auto-clear matching on `edit_mode: external` attributes.
	// `match_strategy` and `fuzzy_config` are only consulted for `external` mode —
	// they are ignored for `approval` mode, which resolves via explicit
	// `:apply` / `:dismiss` endpoints and never auto-clears.
	//
	EditModeConfig *EditModeConfig `json:"edit_mode_config,omitempty"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// When set to true, this attribute will be excluded from search fields.
	// Use this for fields that should not be matched during entity search operations,
	// such as internal hashes or identifiers that might accidentally match search terms.
	//
	ExcludeFromSearch *bool `default:"false" json:"exclude_from_search"`
	// When set to true, this attribute will always be searchable regardless of
	// the ELASTIC_MAX_SEARCH_FIELDS limit. Use this for critical search fields
	// that must always be included in search operations.
	//
	ExplicitSearchable *bool `default:"false" json:"explicit_searchable"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group      *string `json:"group,omitempty"`
	HasPrimary *bool   `json:"has_primary,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon *string `json:"icon,omitempty"`
	// ID for the entity attribute
	ID *string `json:"id,omitempty"`
	// A set of configurations meant to document and assist the user in filling the attribute.
	InfoHelpers *UserRelationAttributeInfoHelpers `json:"info_helpers,omitempty"`
	Label       string                            `json:"label"`
	Layout      *string                           `json:"layout,omitempty"`
	Multiple    *bool                             `default:"false" json:"multiple"`
	Name        string                            `json:"name"`
	// Attribute sort order (ascending) in group
	Order                 *int64  `json:"order,omitempty"`
	Placeholder           *string `json:"placeholder,omitempty"`
	PreviewValueFormatter *string `json:"preview_value_formatter,omitempty"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `json:"protected,omitempty"`
	Readonly  *bool `default:"false" json:"readonly"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string `json:"render_condition,omitempty"`
	// The attribute is a repeatable
	Repeatable *bool `json:"repeatable,omitempty"`
	Required   *bool `default:"false" json:"required"`
	// This attribute should only be active when one of the provided settings have the correct value
	SettingsFlag []SettingFlag `json:"settings_flag,omitempty"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable *bool `json:"show_in_table,omitempty"`
	// Allow sorting by this attribute in table views if `show_in_table` is true
	Sortable       *bool                     `default:"true" json:"sortable"`
	Type           UserRelationAttributeType `json:"type"`
	ValueFormatter *string                   `json:"value_formatter,omitempty"`
}

func (u UserRelationAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserRelationAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserRelationAttribute) GetManifest() []string {
	if u == nil {
		return nil
	}
	return u.Manifest
}

func (u *UserRelationAttribute) GetPurpose() []string {
	if u == nil {
		return nil
	}
	return u.Purpose
}

func (u *UserRelationAttribute) GetConstraints() *UserRelationAttributeConstraints {
	if u == nil {
		return nil
	}
	return u.Constraints
}

func (u *UserRelationAttribute) GetDataClassification() *UserRelationAttributeDataClassification {
	if u == nil {
		return nil
	}
	return u.DataClassification
}

func (u *UserRelationAttribute) GetDefaultValue() any {
	if u == nil {
		return nil
	}
	return u.DefaultValue
}

func (u *UserRelationAttribute) GetDeprecated() *bool {
	if u == nil {
		return nil
	}
	return u.Deprecated
}

func (u *UserRelationAttribute) GetEditMode() *EditMode {
	if u == nil {
		return nil
	}
	return u.EditMode
}

func (u *UserRelationAttribute) GetEditModeConfig() *EditModeConfig {
	if u == nil {
		return nil
	}
	return u.EditModeConfig
}

func (u *UserRelationAttribute) GetEntityBuilderDisableEdit() *bool {
	if u == nil {
		return nil
	}
	return u.EntityBuilderDisableEdit
}

func (u *UserRelationAttribute) GetExcludeFromSearch() *bool {
	if u == nil {
		return nil
	}
	return u.ExcludeFromSearch
}

func (u *UserRelationAttribute) GetExplicitSearchable() *bool {
	if u == nil {
		return nil
	}
	return u.ExplicitSearchable
}

func (u *UserRelationAttribute) GetFeatureFlag() *string {
	if u == nil {
		return nil
	}
	return u.FeatureFlag
}

func (u *UserRelationAttribute) GetGroup() *string {
	if u == nil {
		return nil
	}
	return u.Group
}

func (u *UserRelationAttribute) GetHasPrimary() *bool {
	if u == nil {
		return nil
	}
	return u.HasPrimary
}

func (u *UserRelationAttribute) GetHidden() *bool {
	if u == nil {
		return nil
	}
	return u.Hidden
}

func (u *UserRelationAttribute) GetHideLabel() *bool {
	if u == nil {
		return nil
	}
	return u.HideLabel
}

func (u *UserRelationAttribute) GetIcon() *string {
	if u == nil {
		return nil
	}
	return u.Icon
}

func (u *UserRelationAttribute) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserRelationAttribute) GetInfoHelpers() *UserRelationAttributeInfoHelpers {
	if u == nil {
		return nil
	}
	return u.InfoHelpers
}

func (u *UserRelationAttribute) GetLabel() string {
	if u == nil {
		return ""
	}
	return u.Label
}

func (u *UserRelationAttribute) GetLayout() *string {
	if u == nil {
		return nil
	}
	return u.Layout
}

func (u *UserRelationAttribute) GetMultiple() *bool {
	if u == nil {
		return nil
	}
	return u.Multiple
}

func (u *UserRelationAttribute) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UserRelationAttribute) GetOrder() *int64 {
	if u == nil {
		return nil
	}
	return u.Order
}

func (u *UserRelationAttribute) GetPlaceholder() *string {
	if u == nil {
		return nil
	}
	return u.Placeholder
}

func (u *UserRelationAttribute) GetPreviewValueFormatter() *string {
	if u == nil {
		return nil
	}
	return u.PreviewValueFormatter
}

func (u *UserRelationAttribute) GetProtected() *bool {
	if u == nil {
		return nil
	}
	return u.Protected
}

func (u *UserRelationAttribute) GetReadonly() *bool {
	if u == nil {
		return nil
	}
	return u.Readonly
}

func (u *UserRelationAttribute) GetRenderCondition() *string {
	if u == nil {
		return nil
	}
	return u.RenderCondition
}

func (u *UserRelationAttribute) GetRepeatable() *bool {
	if u == nil {
		return nil
	}
	return u.Repeatable
}

func (u *UserRelationAttribute) GetRequired() *bool {
	if u == nil {
		return nil
	}
	return u.Required
}

func (u *UserRelationAttribute) GetSettingsFlag() []SettingFlag {
	if u == nil {
		return nil
	}
	return u.SettingsFlag
}

func (u *UserRelationAttribute) GetShowInTable() *bool {
	if u == nil {
		return nil
	}
	return u.ShowInTable
}

func (u *UserRelationAttribute) GetSortable() *bool {
	if u == nil {
		return nil
	}
	return u.Sortable
}

func (u *UserRelationAttribute) GetType() UserRelationAttributeType {
	if u == nil {
		return UserRelationAttributeType("")
	}
	return u.Type
}

func (u *UserRelationAttribute) GetValueFormatter() *string {
	if u == nil {
		return nil
	}
	return u.ValueFormatter
}
