// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/provider/typeconvert"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-taxonomy/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *TaxonomyResourceModel) RefreshFromSharedTaxonomy(ctx context.Context, resp *shared.Taxonomy) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Color = types.StringPointerValue(resp.Color)
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.DeletedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.DeletedAt))
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.EnabledLocations = make([]types.String, 0, len(resp.EnabledLocations))
		for _, v := range resp.EnabledLocations {
			r.EnabledLocations = append(r.EnabledLocations, types.StringValue(v))
		}
		r.Icon = types.StringPointerValue(resp.Icon)
		if resp.Kind != nil {
			r.Kind = types.StringValue(string(*resp.Kind))
		} else {
			r.Kind = types.StringNull()
		}
		r.Name = types.StringPointerValue(resp.Name)
		r.Order = types.Float64PointerValue(resp.Order)
		r.Plural = types.StringPointerValue(resp.Plural)
		r.Slug = types.StringPointerValue(resp.Slug)
		if resp.Type != nil {
			r.Type = types.StringValue(string(*resp.Type))
		} else {
			r.Type = types.StringNull()
		}
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *TaxonomyResourceModel) ToOperationsDeleteTaxonomyRequest(ctx context.Context) (*operations.DeleteTaxonomyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	permanent := new(bool)
	if !r.Permanent.IsUnknown() && !r.Permanent.IsNull() {
		*permanent = r.Permanent.ValueBool()
	} else {
		permanent = nil
	}
	var taxonomySlug string
	taxonomySlug = r.Slug.ValueString()

	out := operations.DeleteTaxonomyRequest{
		Permanent:    permanent,
		TaxonomySlug: taxonomySlug,
	}

	return &out, diags
}

func (r *TaxonomyResourceModel) ToOperationsGetTaxonomyRequest(ctx context.Context) (*operations.GetTaxonomyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var taxonomySlug string
	taxonomySlug = r.Slug.ValueString()

	out := operations.GetTaxonomyRequest{
		TaxonomySlug: taxonomySlug,
	}

	return &out, diags
}

func (r *TaxonomyResourceModel) ToOperationsUpdateTaxonomyRequest(ctx context.Context) (*operations.UpdateTaxonomyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	taxonomy, taxonomyDiags := r.ToSharedTaxonomyInput(ctx)
	diags.Append(taxonomyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var taxonomySlug string
	taxonomySlug = r.Slug.ValueString()

	out := operations.UpdateTaxonomyRequest{
		Taxonomy:     taxonomy,
		TaxonomySlug: taxonomySlug,
	}

	return &out, diags
}

func (r *TaxonomyResourceModel) ToSharedTaxonomyInput(ctx context.Context) (*shared.TaxonomyInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	color := new(string)
	if !r.Color.IsUnknown() && !r.Color.IsNull() {
		*color = r.Color.ValueString()
	} else {
		color = nil
	}
	enabled := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled = r.Enabled.ValueBool()
	} else {
		enabled = nil
	}
	enabledLocations := make([]string, 0, len(r.EnabledLocations))
	for enabledLocationsIndex := range r.EnabledLocations {
		enabledLocations = append(enabledLocations, r.EnabledLocations[enabledLocationsIndex].ValueString())
	}
	icon := new(string)
	if !r.Icon.IsUnknown() && !r.Icon.IsNull() {
		*icon = r.Icon.ValueString()
	} else {
		icon = nil
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	order := new(float64)
	if !r.Order.IsUnknown() && !r.Order.IsNull() {
		*order = r.Order.ValueFloat64()
	} else {
		order = nil
	}
	plural := new(string)
	if !r.Plural.IsUnknown() && !r.Plural.IsNull() {
		*plural = r.Plural.ValueString()
	} else {
		plural = nil
	}
	slug := new(string)
	if !r.Slug.IsUnknown() && !r.Slug.IsNull() {
		*slug = r.Slug.ValueString()
	} else {
		slug = nil
	}
	typeVar := new(shared.TaxonomyType)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = shared.TaxonomyType(r.Type.ValueString())
	} else {
		typeVar = nil
	}
	out := shared.TaxonomyInput{
		Color:            color,
		Enabled:          enabled,
		EnabledLocations: enabledLocations,
		Icon:             icon,
		Name:             name,
		Order:            order,
		Plural:           plural,
		Slug:             slug,
		Type:             typeVar,
	}

	return &out, diags
}
